### ISSUE TITLE
Framing not working well

### ISSUE THREAD

**Issue by jorge-jbs** [dafny-lang/dafny#1152]
```dafny
class A {
  function Repr(): set<object>

  predicate Valid()
    reads this, Repr()
}

method Test(a: A, x: object)
  requires x !in a.Repr() && x != a
  requires a.Valid()
  modifies x
{
  assert a.Valid(); // ✅
  modify x;
  assert a.Valid(); // ❌ assertion violation
}
```

`x` is not in `Repr()` and it isn't `a`, so predicate `Valid` should hold true since it only depends on `a` and `Repr()`.

I'm using Dafny 3.0.0. This didn't work in Dafny 2.3.0 neither.

**Comment by wilcoxjay** [comment]
[This is not an answer, but narrows down the problem.]

Something weird is going on with Dafny's ability to reason about the allocatedness of references in `a.Repr()`.

For example, the following assertion fails, but causes the later `assert a.Valid()` to pass:
```
  assert forall y | y in a.Repr() :: allocated(y);  // fails
  // ...
  modify x;
  assert a.Valid();  // now passes
```

Even stranger, in some other contexts, Dafny believes that all sets of objects consist of only allocated objects:

```
lemma Huh(s: set<object>)
  ensures forall y | y in s :: allocated(y);
{}
```

We can use this to create a workaround to get the `Test` method to pass completely.

```
method Test(a: A, x: object)
  requires x !in a.Repr() && x != a
  requires a.Valid()
  modifies x
{
  assert a.Valid();
  Huh(a.Repr());  // needed; otherwise the next line fails
  assert forall y | y in a.Repr() :: allocated(y);
  modify x;
  assert a.Valid();
}
```

This is not a fix, but perhaps narrows down the problem.

**Comment by RustanLeino** [comment]
Thank you for the example, @jorge-jbs , and for the additional exploration, @wilcoxjay . I have several things to say, but perhaps the most helpful point (my last point below) is my suggestion for how to both rewrite the program and get it to verify.

* Dafny (like Java, for example) is a type-safe programming language. This means a program has no dangling pointers and cannot ever dereference unallocated parts of the heap. Dafny carries this design principle into specifications as well. A consequence of this is that quantifications over reference types is always (and implicitly) over _allocated_ objects. This is why lemma `Huh` verifies. (Yes, I'm painfully aware of problem https://github.com/dafny-lang/dafny/issues/19, which is on my to-do list to fix.)

* The property that would let you prove that `modifies x;` has no effect on the value of `a.Valid()` is called the _frame axiom_. The frame axiom essentially formalizes the `reads` clause of a function, and Dafny generates one frame axiom for each function. For a function like

    ``` dafny
    function F(x: X): Y
      reads R
    ```

    the frame axiom looks something like

    ```
    forall h0: Heap, h1: Heap, x: X ::
      HeapSuccession(h0, h1) &&
      (forall obj :: obj in R ==> h0[obj] == h1[obj])
      ==>
      F(h0, x) == F(h1, x)
    ```

    where I'm using some (non-Dafny) notation to explicitly quantify over heaps, using `HeapSuccession(h0, h1)` to say that `h0` and `h1` are two valid heaps and where `h1` comes later in time than `h0`, and using the notation `h[obj]` to denote the values of the fields of `obj` in heap `h`. In words, the frame axiom says that for any heap `h0` followed later in time by a heap `h1`, where `h0` and `h1` agree on the state of the objects in `R`, we have that function `F` applied to `x` gives the same result in both heaps `h0` and `h1`.

    Now, one can imagine making this frame axiom easier to use by restricting the quantification over `obj` to just allocated objects. This would let you prove the `Test` method above.

    ```
    forall h0: Heap, h1: Heap, x: X ::
      HeapSuccession(h0, h1) &&
      (forall obj :: obj is allocated in h0 && obj in R ==> h0[obj] == h1[obj])
      ==>
      F(h0, x) == F(h1, x)
    ```

    Alas, this is not sound, because it would let you prove `F(h0, x) == F(h1, x)` for any `h0, h1, x`:  Let `UrHeap` be the heap at the beginning of time when nothing has been allocated. Then, the altered frame axiom above would let you prove `F(UrHeap, x) == F(h0, x)` and also `F(UrHeap, x) == F(h1, x)`, from which `F(h0, x) == F(h1, x)` follows.

    (For the record, the altered frame axiom can be implemented by simply changing `AlwaysUseHeap` to `CommonHeapUse` on [line 5804 of Translator.cs](https://github.com/dafny-lang/dafny/blob/master/Source/Dafny/Translator.cs#L5804). As an example of the unsoundness that this change brings about, the assertion on [line 37 of dafny4/Bug146.dfy](https://github.com/dafny-lang/dafny/blob/master/Test/dafny4/Bug146.dfy#L37) then becomes provable.)

* There's another axiom that one can try to alter, the so-called _consequence axiom_ of the function. For my function `F`, the consequence axiom essentially says

    ```
    forall h: Heap, x: X ::
      GoodHeap(h) &&
      Is(x, X)
      ==>
      Is(F(h, x), Y)
    ```

    where I'm using `GoodHeap(h)` to express that `h` is a valid heap and `Is(x, X)` to say that `x` has a value of type `X`.

    One can imagine strengthening the consequent of this axiom with something that says the result is allocated. Such an axiom is sound only if it also requires all parameters to be allocated. (For example, suppose types `X` and `Y` are the same and `F` simply returns its argument, `x`. Then, it would be unsound to conclude that `F(h, x)` is allocated in `h` without first knowing that `x` is.) A sound alternative consequence axiom is:

    ```
    forall h: Heap, x: X ::
      GoodHeap(h) &&
      IsAlloc(x, X, h)
      ==>
      IsAlloc(F(h, x), Y, h)
    ```

    where I'm using `IsAlloc(x, X, h)` to say that `x` has type `X` and is allocated in heap `h`. (Implementation note: If one were to incorporate this axiom, it should be in addition to the existing consequence axiom. Furthermore, the matching pattern for the quantifier should be the `IsAlloc(F(h, x), Y, h)` expression in the consequent. This also works for functions that do not take the heap as an argument, that is, functions with empty `reads` clauses.)

    While sound, this axiom is expensive, because it requires the antecedent `IsAlloc(x, X, h)` to be proved each time the consequence axiom is used. This axiom would cause many more `IsAlloc` terms to be added to each proof context, which may (be okay, but may also) make the verifier work much harder for the little gain.

    (Years ago, we had a similar consequence axiom, but improved it to the one Dafny has today. I may have expressed it a bit more cleanly above than I remember from before, so maybe this is worth an experiment. My gut feeling is that it would make many verifications worse.)

* One may expect that @wilcoxjay 's workaround above could be replaced by a simple assertion

    ``` dafny
    assert allocated(a.Repr());
    ```

    Alas, this does not work, because of the current weaker consequence axiom.

    (For a long time, I've wanted to see these sorts of things incorporated into forms of the `reveal` statement. Maybe that will happen in the future.)

* Finally, after those gloomy remarks, there is something you can do, and I suggest you do it. Encode `Repr` as a ghost field, not a function. A function may work for very simple objects, and in those cases removes the need to update the `Repr` field in code. However, for recursive data structures, it is very difficult (if not impossible) to get verifications to go through if `Repr` is a function. The reason is that a `Repr()` function also has a `reads` clause, and any change in the heap may cause the evaluation of that `reads` clause to change.

    Therefore, I suggest you stay with the standard specification idiom in Dafny, see sections 8 and 9 of this [older tutorial](http://leino.science/papers/krml221.pdf), or [class `Point` in `Test/dafny4/FlyingRobots.dfy`](https://github.com/dafny-lang/dafny/blob/master/Test/dafny4/FlyingRobots.dfy#L16).

    Your (verifying) program will then look like:

    ``` dafny
    class A {
      var Repr: set<object>

      predicate Valid()
        reads this, Repr
    }

    method Test(a: A, x: object)
      requires x !in a.Repr && x != a
      requires a.Valid()
      modifies x
    {
      assert a.Valid();
      modify x;
      assert a.Valid();
    }
    ```
