### ISSUE TITLE
(soundness issue) ghost methods & lemmas should disallow `decreases *`

### ISSUE THREAD

**Issue by tjhance** [dafny-lang/dafny#1172]
A lemma that uses `decreases *` can easily ensure `false`. Of course, to do so, it needs to be nonterminating.

However, a nonterminating `ghost method` will be erased in compiled code. This allows us to write a program that passes verification but crashes at runtime:

```
ghost method f()
decreases *
ensures false
{
  f();
}

method Main()
decreases *
{ 
  f();
  
  var x := 1 / 0;
} 
```

**Comment by parno** [comment]
I'm not sure that this is morally different from writing 
```
lemma {:axiom} f()
    ensures false
```
Once you write `{:axiom}` or `decreases *`, you as the programmer are taking responsibility for getting the post-conditions right.  And the fact that `decreases *` propagates, in this case up to `Main`, makes it clear to the caller/inspector of the `Main` that the verification results may be unsound.  Having the option to mark a lemma as `decreases *` seems plausibly useful in cases where you don't want to prove termination, but you're confident about your argument.

**Comment by RustanLeino** [comment]
A `decreases *` should just have the effect of changing termination-sensitive verification to termination-insensitive verification. In other words, a program that uses `decreases *` may fail to terminate, but should otherwise operate without crashes and according to all specifications.

Therefore, allowing `decreases *` on a `ghost method` or `lemma` is a bug. (And it's a bug that surprises me.)

I think of attributes as playing a different role. They are directives that ask the tool to deviate from its standard (sound) behavior to accommodate some practical consideration. For example, `{:axiom}` tells the compiler not to generate a "no body" error, and says that you're willing to take responsibility for that such a body could exist. `{:extern}` asks the compiler to generate calls to a method/function that is implemented outside the Dafny program, and says that you're taking responsibility for the correctness of that implementation. So, `{:axiom}` and `{:extern}` could cause crashes in Dafny code if the programmer fails to live up to the responsibility that comes with using these, but `decreases *` should not.

**Comment by parno** [comment]
Interesting, I hadn't realized that Dafny continued to verify non-termination conditions even after a decreases *.
