### ISSUE TITLE
Regression in compilation error messages (was: Dafny CLI compiler gives worse error details than VSCode's Language Server)

### ISSUE THREAD

**Issue by hmijail** [dafny-lang/dafny#1174]
Dafny 3.0.0.30204 (commit d25ae2577b5d38b3b4df90a7e8062d3f6fbfd2a7)
dotnet 5.0.104
macOS 11.2.3
VSCode 1.55.1 with Dafny extension 1.4.0

I'm compiling the following bad example program with the CLI compiler. 
```
function fm1(): bool
{
    (true)
}

function method fm2():bool
{
    var v := fm1();
    (v)
}
```

Compilation fails as expected. The problem is that it emits an unhelpful/misleading error text, attributing it to a point in the source code where it makes no sense.
In contrast, VSCode shows a great message at the correct point in the code. See screenshot with both the CLI result and the IDE message.
![Screen Shot 2021-04-09 at 1 28 05 pm](https://user-images.githubusercontent.com/4139546/114124320-87786f00-9937-11eb-8db6-a5b44081ba10.jpg)

Is there a way to make the CLI compiler emit that same level of information? I haven't been able to find a flag to do so. If there is no such a way, please consider this a Feature Request.

**Comment by camrein** [comment]
For anyone wondering about the different error messages (language server vs compiler): I have quickly tested the provided example. The different error messages encountered between the language server and compiler are because there must be compiler (and possibly language) changes leading to this new behavior.
The language server used by the VSCode extension (if not changed) compiles against the latest public release of the Dafny compiler (v3.0.0) and as far as I can tell is the compiler used here is a more recent version. Updating the language server (currently in progress with PR #1173) to the latest Dafny compiler master yields the same error messages.

**Comment by hmijail** [comment]
Do you mean that once the language server is updated the IDE messages will be as bad as the CLI compiler's?

**Comment by hmijail** [comment]
I can confirm that if I use the dafny installed by homebrew (which reports version 3.0.0.30203), the result is the same as the IDE shows:
```
$ dafny example.dfy
/Users/mija/programming/ConsenSys/IBFTDesign/reduction2/example.dfy(9,13): Error: function calls are allowed only in specification contexts (consider declaring the function a 'function method')
1 resolution/type errors detected in example.dfy
```
Which I guess means that the change that worsened the compilation error messages happened between 3.0.0 and commit d25ae2577b5d38b3b4df90a7e8062d3f6fbfd2a7.

**Comment by camrein** [comment]
I can't really tell if the error messages got worse. Maybe there were language changes I am unaware of that relaxed the restrictions when using functions within function methods - or you may have encountered a bug. Probably someone else can shed some light on these observations.

**Comment by RustanLeino** [comment]
There was a language change that would explain the difference between the two error messages you mention. However, the change was already included in Dafny 3.0.0 (I think it was implemented sometime last fall). The new message is the one you're calling "worse" above. Here's the change:

Before 3.0.0, Dafny would complain that the let expression `var v := fm1(); v` tries to assign a ghost expression (namely, `fm1()`) to a non-ghost variable (namely, `v`). This error was thus reported the RHS of the binding, namely on the `fm1()` call.

In Dafny 3.0.0, the declaration of variable `v` is automatically "upgraded" to `ghost`, because its initializing expression (`fm1()`) is ghost. Because of this _auto-ghost_ feature, `v` is a ghost variable, and since the let expression returns `v`, the let expression is ghost, and this gives you a complaint that the body of the non-ghost `fm2` is trying to return a ghost expression (namely, `v`).

A restricted version of this auto-ghost feature has been in Dafny for 10-or-so years, where it applied only to certain out-parameters of methods. In Dafny 3.0.0, we made auto-ghost standard for all variable declarations with initializing expressions.

So, what remains puzzling to me is how the IDE gave you that old error message in the first place.

**Comment by hmijail** [comment]
Thank you for the explanations.
I understand that given those changes, pinpointing the source of error might get complicated. Still, I guess it's either the compiler keeping track of the auto-ghosting and where it caused a problem, or it's the human having to do it. I'd hope the compiler would do it... So, please consider this issue as a Feature Request for more informative error messages.

As another concrete example: the compiler's message is useless to know where exactly was the problem. 
![Screen Shot 2021-04-11 at 11 41 09 am](https://user-images.githubusercontent.com/4139546/114289486-ae5fae00-9abb-11eb-97be-5e7fffc70526.jpg)

These are all simplifications of my real code, in which I was able to fix problems (as a noob!) thanks to the IDE while my more experience colleague was bogged down reducing the problematic code until the CLI compiler's message changed. The moment he realized I was getting these hints from the IDE we both started looking for compiler flags to enable them; that was the origin of the present issue.

**Comment by hmijail** [comment]
(deleted a comment because I realized I was using a bad example)

**Comment by keyboardDrummer** [comment]
@hmijail does Rustan's explanation answer your question as to why the error reporting changed?

**Comment by hmijail** [comment]
Yes, the explanation makes sense and answers the question. 
I still think the error message could be clearer, but I'm still a Danfy newbie, so  I can be wrong.

The error messages are in the screenshot, but in case you just want them in text, here they are:
old: "Error: function calls are allowed only in specification contexts (consider declaring the function a 'function method')"
new: "Error: ghost variables are allowed only in specification contexts"

**Comment by keyboardDrummer** [comment]
> The error messages are in the screenshot, but in case you just want them in text,

Ah, sorry I didn't realise both were in the screenshot.

> I still think the error message could be clearer, but I'm still a Danfy newbie, so I can be wrong.

Do you mean something like "Error: ghost variables such as `z` are allowed only in specification contexts. `z` was inferred to be ghost from its initial assignment." ?

**Comment by hmijail** [comment]
Yes, something like that would be an improvement.
