### ISSUE TITLE
Replacing a literal with a constant leads to proof failure

### ISSUE THREAD

**Issue by seanmcl** [dafny-lang/dafny#1179]
Working with bitvectors in the 3.0.0 release, I noticed the following:

```
const size := 3
const one := 1 as bv3
const mone := -one

predicate method diff(v1: bv3, v2: bv3, i: nat)
  requires i < size
{
  (v1 >> i) & one != (v2 >> i) & one
}

lemma find1(v1: bv3, v2: bv3) returns (i: nat)
  requires v1 != v2
  ensures i < size
  ensures diff(v1, v2, i) {
    i := 0;
    while (i < 3)
      invariant (mone >> (3 - i)) & v1 == (mone >> (3 - i)) & v2
    {
      if diff(v1, v2, i) {
        return i;
      }
      i := i + 1;
    }
  }
```

verifies.  If I replace the 3 in the while guard with `size` whose value is the same, the proof no longer passes:

```
$ dafny /compile:0 /tmp/foo.dfy
/tmp/foo.dfy(16,4): Error: A postcondition might not hold on this return path.
/tmp/foo.dfy(13,12): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    /tmp/foo.dfy(16,5): anon9_LoopHead
    (0,0): anon9_LoopBody
    /tmp/foo.dfy(16,5): anon10_Else
    (0,0): anon11_Then
/tmp/foo.dfy(17,22): Error: shift amount must be non-negative
Execution trace:
    (0,0): anon0
    /tmp/foo.dfy(16,5): anon9_LoopHead
    (0,0): anon9_LoopBody
    (0,0): anon10_Then
/tmp/foo.dfy(17,48): Error: shift amount must be non-negative
Execution trace:
    (0,0): anon0
    /tmp/foo.dfy(16,5): anon9_LoopHead
    (0,0): anon9_LoopBody
    (0,0): anon10_Then
```

**Comment by RustanLeino** [comment]
The error messages point out that the verifier can't prove (either of the two occurrences of) `3 - i` to be non-negative and can't prove the postcondition `i < size`. To prove these, you need to declare another loop invariant:

``` dafny
invariant i <= size
```

This is expected behavior. If you add the loop invariant, your program verifies.

But a mystery remains: Why was this loop invariant not necessary when the loop guard was `i < 3`? The answer is that the verifier (more precisely, a simple abstract interpreter in Boogie, which supports interval analysis with thresholds) can infer some simple invariants involving _one_ variable and literal constants, like `0` and `3`. For many prototypical loops where a loop index starts at `0` and is increased in the loop, this abstract interpreter finds the lower bound `0 <= i`. It will not infer a symbolic upper bound, like `i <= size`, but if the upper bound is known to Boogie as a literal constant, then an upper bound, like `i <= 3`, is sometimes also found. So, in your example, when you use the guard `i < 3`, Boogie is able to discover the loop invariant `0 <= i <= 3`, but when the guard is `i < size`, Boogie infers only `0 <= i`.
