### ISSUE TITLE
Verification vs compilation of a file with let-such-that expression errors

### ISSUE THREAD

**Issue by hmijail** [dafny-lang/dafny#1190]
I have a file that uses let-such-that in function methods.
It fails verification with an error message like `Error: to be compilable, the value of a let-such-that expression must be uniquely determined`.

Interestingly, the file seems to compile correctly (no error messages) if verification is disabled, either because of `/noVerify` or because it's used as an included module.

Is the resulting compilation product good to use?

**Comment by RustanLeino** [comment]
The results will not be sound, that is, the compiled code may not correspond to what is verified. For example, with

``` dafny
method Main() {
  var A := {4, 6};
  var B := {6, 4};
  var a, b := F(A), F(B);
  assert A == B;
  assert a == b;
  print a, " ", b, "\n";
}

function method F(S: set<int>): int
  requires S != {}
{
  var x :| x in S;
  x
}
```

the Go compiler produces

```
$ dafny test.dfy /compile:4 /compileTarget:go
test.dfy(13,2): Error: to be compilable, the value of a let-such-that expression must be uniquely determined
Execution trace:
    (0,0): anon0
    (0,0): anon6_Else
    (0,0): anon7_Then

Dafny program verifier finished with 1 verified, 1 error
Wrote textual form of target program to test-go/src/test.go
Additional target code written to test-go/src/dafny/dafny.go
Additional target code written to test-go/src/System_/System_.go
Running...

4 6
```

The issue is that every expression in Dafny is like a mathematical expression in that it is a function of its arguments. This means that if you evaluate it twice with equal arguments, then you get the same results. That's what the verifier expects, but achieving this at run time is expensive. Therefore, Dafny leaves it to programmers to ensure this when the property is needed.

For more information, see [Compiling Hilbert's epsilon operator](https://easychair.org/publications/paper/dM).
