### ISSUE TITLE
Non-reference traits

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/dafny#1226]
Currently, a `trait` in Dafny always denotes a reference type. For example, for every trait declaration `T`, there are two types, the non-null `T` and the nullable `T?`. There are many useful applications where it would be nice to allow non-reference types to extend a `trait` as well. This Issue requests that every type be able to extend traits.

Implementation notes:
* This is a large change, which I expect to take several months to implement. A recent change to traits was to let traits support type parameters. That change was started in May 2020, and with some breaks during summer 2020, the changes were finished in the last quarter of 2020. One of the big work pieces was to get type inference to work sensibly. Another of the big work pieces was to map Dafny's traits, type parameters, and co/contra-variance work to the target compilers. (Actually, the C# and Java backends still don't support variance for some types.) Some of these changes did not relate directly to traits, but were necessary to get traits to work out. For example, the machinery for run-time type descriptors was reworked as part of the change. In a similar way, I imagine we will discover other issues that need to be addressed to make traits support non-reference types.
* Compilation will also require some thought. For example, should fat pointers be used and how does that effect performance? The article https://lukasatkinson.de/2018/interface-dispatch/ provides good food for thought.
* As a step in this direction, Dafny 3.0.0 started allowing `object` to be listed in the `extends` list of traits and classes. At the moment, doing so has no effect, but the idea in the future will be that traits that extend `object` will be limited to reference types.

**Comment by robin-aws** [comment]
I'd like to mention another potential language improvement that would build on this, and is hence worth considering in the design for this one.

Dafny currently has several built-in type characteristics, used to restrict the subset of types that can be used in a given context. Some have explicit names that can be used to restrict type parameters, such as `(0)` or `(!new)` (https://dafny-lang.github.io/dafny/DafnyRef/DafnyRef#sec-type-characteristics). There are also arguably one or two implicit type characteristics, such as "failure-compatible" (https://dafny-lang.github.io/dafny/DafnyRef/DafnyRef#sec-update-failure) and the "strictly smaller" ordering used by decreases clauses (https://dafny-lang.github.io/dafny/DafnyRef/DafnyRef#513-decreases-clause).

The short identifiers used for explicit type characteristics can be less than immediately readable (I challenge anyone to convince me that the meaning of `(00)` is obvious :). Implicit type characteristics can be even harder to understand, and since user code cannot reference them it's not possible to have higher-order helper logic on "failure-compatible" types, for example.

If this issue extends traits so that they can be used for any Dafny type, I would be very happy to replace the notion of "type characteristics" with traits, so that any generalization or restriction over types would have a unified expression. I really like the idea of defining these concepts using Dafny itself - for example, the "non-empty" type characteristic `(00)` would translate into the assertion `exists x: T`, whereas "auto-initializable" `(0)` would translate into `function Default(): T`. Being able to "Go To Definition" on the symbol "FailureCompatible" in the IDE, which would navigate to that trait's definition in the Dafny prelude, would provide a much more natural way for users to discover and understand the concepts.

This could also provide a natural way to access and customize the built-in termination metric order as requested in #762.

cc @RustanLeino

**Comment by RustanLeino** [comment]
Fixed by https://github.com/dafny-lang/dafny/pull/4600, currently under the `--type-system-refresh --general-traits:datatype` options, but soon to become the default.
