### ISSUE TITLE
How to compile dafny against a custom Boogie?

### ISSUE THREAD

**Issue by cpitclaudel** [dafny-lang/dafny#1310]
Hi folks,

Now that the Boogie submodule is gone (@bkragl  95b86f7afab05f30ef5b20730e0468263824bdbf), can we update the INSTALL file to explain how to build against a custom Boogie (before it was enough to just modify the submodule-d version of Boogie).  (I have no experience  with NuGet)

CC @wilcoxjay

**Comment by robin-aws** [comment]
I think your best bet is probably to publish your customized Boogie to a "local NuGet feed", meaning a directory on your own disk where you can stick a built package for other packages to consume as if they came from the central NuGet gallery: https://docs.microsoft.com/en-us/nuget/hosting-packages/local-feeds

I haven't actually tried this recently, but I'm going to in order to test out some changes to the https://github.com/dafny-lang/dafny.msbuild build tasks. If you figure out what works before I do feel free to add the instructions to the wiki! :)
