### ISSUE TITLE
Linter to catch accidental implication capturing?

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#1311]
I've noticed it's very easy to fall into this trap:
```dafny
assert
  && A
  && B ==> C
  && D;
```

The intention is for this to mean:
```dafny
assert A && (B ==> C) && D;
```

But the `==>` operator binds more weakly than `&&`, so it actually means:
```dafny
assert (A && B) ==> (C && D);
```

This can easily lead to assertions that are vacuously true, and thus pass verification but fail to model the actual requirements correctly.

The only easy solution I can think of is a linter to warn against this somehow. Another possibility is a synonym for `&&` that binds more weakly, and perhaps could be read more naturally when used as a leading unary operator as above?

**Comment by robin-aws** [comment]
Perhaps defining a less fragile idiom for formatting large, complex, multi-line boolean expressions might be the deeper solution here. I also find that these can be hard to read when mixing in qualifiers like `forall` and `exists`, and even `match` expressions.

**Comment by RustanLeino** [comment]
Another common mistake that the same linter could look for:

``` dafny
&& A
&& forall x :: P(x) ==> Q(x)
&& B
```

**Comment by keyboardDrummer** [comment]
Another solution could be an editor that adds coloured underlines to subtrees of the expression tree to indicate the tree structure.

**Comment by robin-aws** [comment]
I agree that the idea of linting for this is underspecified and may not actually make sense by itself.

I'm starting to like the idea of using `that` as a lower-precedence version of `&&`, as it seems to read really nicely in a lot of these contexts:

```dafny
assert
  that A
  that forall x :: P(x) ==> Q(x)
  that B;
```

With that in place (ha), the linter could give a stronger recommendation not to break `&&` chains across lines.

**Comment by keyboardDrummer** [comment]
Is using an alphanumeric word as an operator something that happens elsewhere in Dafny? It looks like functional style function calls to me.

Alternatively, we could consider adding a suffix operator with low precedence, that can be used to break an expression, like `;`.

```
assert
  && A
  && forall x :: P(x) ==> Q(x);
  && B
```

**Comment by tjhance** [comment]
I like the idea of a warning rather than new syntax. Incidentally, I think Dafny already has a similar built-in warning if you write `exists x :: a ==> b`, and I've had it save me in the past.

Personally, if I write,

```
&& A
&& B ==> C
&& D
```

it's _always_ a mistake (if I meant to write it like that, I would have indented it differently).

The "new syntax" approach both complicates the language, but it also doesn't help out newer users as much. The thing about introducing a new syntax as a solution is that, yeah, it helps experienced users like ourselves, if we know to use that syntax by default, but it doesn't actually help a novice who accidentally writes `&& a ==> b` and doesn't understand why their code doesn't verify.

**Comment by robin-aws** [comment]
@keyboardDrummer Yeah, I had similar thoughts about using collections to avoid using the `&&` operator. `true in {...}` works for disjunction, but conjunction is the more common case and I can't see a similar simple trick. Plus I suspect it would make things more difficult for the verifier. 

You could rely on some functional staples being in the standard library and do something like `all([A, B ==> C, D])` in the style of Python's `all` function, and similarly `any` for disjunction.

@tjhance That's an interesting point about intentation. An alternative solution to this is to work towards having a widely-used Dafny auto-formatter in the style of `gofmt`, and rely on it re-writing our example to something like: `(A && B) ==> (C && D)`, at which point the user will hopefully spot that in review and say wait a minute, that's not what I meant.

**Comment by robin-aws** [comment]
> accidentally writes && a ==> b and doesn't understand why their code doesn't verify.

For the record, that's actually the less harmful case and I'm less worried about that. It's very common for `(A && B) ==> C` to be a much weaker condition than `A && (B ==> C)`, and hence often your code DOES verify but you have a modelling bug, because you didn't prove the post-condition your code actually needs to have.

**Comment by keyboardDrummer** [comment]
> Yeah, I had similar thoughts about using collections to avoid using the && operator. true in {...} works for disjunction, but conjunction is the more common case and I can't see a similar simple trick. Plus I suspect it would make things more difficult for the verifier.

Oops, didn't realise my example was for conjunction, updated it now, but I think using `false !in {A, B}` should work for disjunction.

**Comment by keyboardDrummer** [comment]
> An alternative solution to this is to work towards having a widely-used Dafny auto-formatter in the style of gofmt, and rely on it re-writing our example to something like: (A && B) ==> (C && D), at which point the user will hopefully spot that in review and say wait a minute, that's not what I meant.

Interesting!

**Comment by robin-aws** [comment]
Another possibility I just thought of, inspired by `calc` statements and @keyboardDrummer's suggestion of using `;` to delineate clauses (which I realized `calc` statements already do). It's a little half-baked and probably needs some tweaking to not cause parsing ambiguity.

```dafny
assert {
  A;
  forall x :: P(x) ==> Q(x);
  B;
}
```

The idea being that curly braces can be used in a context that expects an expression instead of a block. The sub-expressions, which must be terminated with `;`, are combined with a single common operator. By default this would be `&&`, but you could override that just as in calc statements, e.g. `assert || { A; B; C; }`

This could help improve the readability of some of the really large postconditions I've seen:

```dafny
ensures match res
  case Failure(e) => true
  case Success(x) => {
    A;
    B;
    exists y {
      ValidFoo(x, y);
      C;
      D;
      E ==> {
        ...
      }
      ...
    };
    ...
  }
```

**Comment by mschlaipfer** [comment]
Wondering if there could be a purely visual way of showing the applied operator binding in the IDE. The difficulty would be to not overwhelm the user with irrelevant information.

**Comment by keyboardDrummer** [comment]
> Wondering if there could be a purely visual way of showing the applied operator binding in the IDE. The difficulty would be to not overwhelm the user with irrelevant information.

We could show the code contained in the expression AST node when hovering over the node's operator in the hover popup menu.

**Comment by kjx** [comment]
So I just spent a couple of days thinking I was chasing down a dafny bug but it turned out to be this error.
I've attached an example file [vh28iBUG.txt](https://github.com/dafny-lang/dafny/files/9762644/vh28iBUG.txt)

For what it's worth,  most of these fixes feel to me just like fixes: 
trying to patch over issues with the syntax design.  My preferred
solution would be to fix up the syntax to avoid these problems.

In this case, seems "forall" should be treated as a 
unary prefix clause with the same precedence as 
"&&" and "||" so:

```
    a
    && forall o <- objects :: b
    && c
```

would be treated the same way as 

```
   a
    && (forall o <- objects :: b)
    || c
```

Failing that, rather than linters or IDE visualisations,
why not adopt the go / Smalltalk solution of a standard
formatter, and a format that would makes this structure clear. 
If you're going to start doing layout syntax, do it consistently
you can probably manage  to get rid of all the semicolons
in the imperative syntax, and take the opportunity to clean
up things like if, var vs let, and all the rest...
