### ISSUE TITLE
Support {:opaque} attribute in constants

### ISSUE THREAD

**Issue by amaurremi** [dafny-lang/dafny#1338]
Currently, functions in Dafny can be declared with an `{:opaque}` attribute, which hides the function implementation from the verifier unless it is explicitly revealed. It would be useful to have the same functionality for constants: being able to declare
```const {:opaque} x := ...```
which would make the definition of `x` hidden.

**Comment by cpitclaudel** [comment]
For opaque functions the expectation is that you'll use the ensures clause; what can you do with opaque constants?

Note that there is also a workaround for this, which is to not `reveal` the constant; is that acceptable?

**Comment by cpitclaudel** [comment]
Following up on my previous, here are various implementations of opaque constants:

1. Using an opaque function instead.
   Every use needs parentheses, but you get a reveal lemma
   and you can add ensures

```dafny
module OpaqueFunction {
  function method {:opaque} x(): nat ensures x() != 2 { 1 }
}
```

2. Using a constant defined with a function.
   Same as (1) but with nicer syntax at use sites

```dafny
module ConstantFromFunction {
  function method {:opaque} X(): nat ensures X() != 2 { 1 }
  const x := X();
}
```

3. Using an `export provides` declaration.
   No free ensures or reveal (need to add lemmas for those)

```dafny
module ExportProvides {
  export provides x
  const x := 1
}
```

4. Using a library function to opacify.
   Pretty lightweight.  Gives you a `reveal` but no `ensures`

```dafny
module Helpers {
  function method {:opaque} Opaque<A>(a: A): A { a }
}

module WithHelper {
  import opened Helpers
  const x := Opaque(1);
}
```

All four of these prevent you from proving the equalities below:

```dafny
method M() {
  assert OpaqueFunction.x() == 1;
  assert ConstantFromFunction.x == 1;
  assert ExportProvides.x == 1;
  assert WithHelper.x == 1;
}
```

FWIW, I like option 4.  I would like to understand the use case better to make sure that we don't implement the wrong thing.

**Comment by txiang61** [comment]
We had to hide the definition of `const` for verification stability, but still want to compile that `const` as a field and not as a method. We are currently using option 1 with a compiler work around which compile that method as a const, but we would like to remove that work around in the compiler.

**Comment by cpitclaudel** [comment]
Here is a proposal (co-written with @fabiomadge) on how to implement this. 

Background: Dafny uses fuel to implement opacity and `reveal` on functions.  This is because functions may be opaque, so simply revealing their bodies unconditionally is not enough: we need to also just give them a bit of fuel.  So, instead, the `reveal` axiom says that the default fuel that the opaque function is called with is equal to `2 + …`, which is enough to unfold the function.

Constants do not use fuel (and cannot be recursive, at least for now), so we need a different encoding. Start with this file:

```dafny
datatype D = D(x: int) { const TransparentConstant := this.x; }
method Test() { assert D(1).TransparentConstant == 1; }
```

Dafny generates this:

```boogie
function _module.D.TransparentConstant(this: DatatypeType) : int;

axiom (forall this: DatatypeType :: 
  { _module.D.TransparentConstant(this): int } 
  _module.D.TransparentConstant(this): int == _module.D.x(this));
```

Removing the `axiom` causes the `assert` in the `Test` method to fail, which is what we want.  We propose to replace the axiom by a `reveal` method:

```
procedure reveal__module.D.TransparentConstant();
  free ensures (forall this: DatatypeType :: 
    { _module.D.TransparentConstant(this): int } 
    _module.D.TransparentConstant(this): int == _module.D.x(this));
```

Then, as expected, adding an explicit `call reveal__module.D.TransparentConstant();` before the assert makes it pass.

There are two more axioms that Dafny defines about the constant:

```
// D.TransparentConstant: Type axiom
axiom 0 < $FunctionContextHeight
   ==> (forall $o: DatatypeType :: 
    { _module.D.TransparentConstant($o) } 
    $Is(_module.D.TransparentConstant($o), TInt));

// D.TransparentConstant: Allocation axiom
axiom 0 < $FunctionContextHeight
   ==> (forall $h: Heap, $o: DatatypeType :: 
    { _module.D.TransparentConstant($o), $IsAlloc($o, Tclass._module.D(), $h) } 
    $IsGoodHeap($h) && $IsAlloc($o, Tclass._module.D(), $h)
       ==> $IsAlloc(_module.D.TransparentConstant($o), TInt, $h));
```

Should these, too, become `free ensures` clauses of the `reveal` procedure? Or should they remain always-available axioms?  CC @RustanLeino .

**Comment by RustanLeino** [comment]
The proposal of turning the definition axiom into a definition procedure-ensures for opaque const's looks good. The Type axiom and Allocation axiom should always be available.

**Comment by cpitclaudel** [comment]
Thanks Rustan!
