### ISSUE TITLE
"Assume" in predicates cause code unable to compile

### ISSUE THREAD

**Issue by superymk** [dafny-lang/dafny#1497]
Hi, I put assume statements to reduce proof effort, see the code below:

```
predicate P(x:int)
{
    assume x == 1;
    
    (x == 1)
}

method Func(x:int) returns (y:int)
    requires P(x)
{
    return (x+1);
}
```

But both the command `E:/utils/dafny-v3.2/Dafny.exe a.dfy` and `E:/utils/dafny-v3.2/Dafny.exe /compile:2 /noVerify a.dfy` report the same error: 
`a.dfy(3,4): Error: an assume statement cannot be compiled`

I expect the code can be compiled because there are no assumptions in the implementation context.
Thanks!

**Comment by robin-aws** [comment]
Hi there! The `expect` statement is your friend here: unlike `assume`, it CAN be compiled, and introduces a runtime check of the boolean expression: https://dafny-lang.github.io/dafny/DafnyRef/DafnyRef#sec-expect-statement

**Comment by robin-aws** [comment]
I responded too quickly, as I didn't spot you were trying to make this assumption in a `predicate` in your example, where `expect` is not allowed. :) You will likely have to refactor your code if you want to compile it but include unverified assumptions via `expect`.

**Comment by superymk** [comment]
I see, thanks!

**Comment by MikaelMayer** [comment]
The change to support that would be easy. It's a matter of wrapping this line with an if in case it's a ghost function.

https://github.com/dafny-lang/dafny/blob/51972e730e34b7d95d3f736dba3cc39dafec9483/Source/Dafny/Compilers/Compiler.cs#L1764

where v is a visitor that checks the absence of assumptions.

However, because Dafny is a programming language with verification power, we have to guarantee soundness and we need to minimize any source of unsoundness. This is probably why the only way to introduce unverified code is using an attribute like `{:axiom}`, which is not part of the language. The problem with your code, is that it would be easy to forget about this assume since it's part of the syntax.

I suggest the following workaround so that you can take responsibility of any unsoundness and so that compilation works without workaround:

```
predicate P(x:int)
{    
    do_assume(x == 1) && x == 1
}

function {:axiom} do_assume(x: bool): (r: bool) ensures x == r
```
