### ISSUE TITLE
let expressions in `forall`

### ISSUE THREAD

**Issue by seebees** [dafny-lang/dafny#1545]
using `is` and `as` in `forall` (and I suspect `::`) do not work as expected.
If I start from these examples:

https://github.com/dafny-lang/dafny/blob/master/Test/triggers/let-expressions.dfy

```dafnypredicate Foo(s: seq<int>)
{
    && (forall i :: 0 <= i < |s| ==> var j := i; s[j] > 0)
    && (forall i :: 0 <= i < |s| ==> var j, k := i, i; s[k] > 0)
    && (forall i :: 0 <= i < |s|-1 ==> s[i] == s[i+1])
    && (forall i :: 0 <= i < |s|-1 ==> s[i] == var j := i+1; s[j])

    // Works
    && (forall i | i in s ::
      && i is nat
      && var j := i as nat;
      && j in s)

    // Does not work
    && (forall i :: 0 <= i < |s| ==>
      && i is nat
      && var j := i as nat;
      && s[j] > 0)

    && (forall i :: 0 <= i < |s| ==>
      && s[i] is nat
      && var j := s[i] as nat;
      && s[j] > 0)
}
```

There are also more complex issues with classes.
The `as` statement does not work as well.
I found that using the `forall i | i in s`
along with a predicate that takes the correct new `as` class _would_ work.

**Comment by MikaelMayer** [comment]
When you say "does not work", can you explain what is the error message exactly?

**Comment by keyboardDrummer** [comment]
@MikaelMayer I believe you, but could you add more data as to how the improved hint resolves this issue?

**Comment by MikaelMayer** [comment]
You're right, I should say it. The issue was actually not in the let expression.
After interacting with @seebees  directly I was able to reproduce the error on this minimalistic example:

```
1: predicate Foo(s: seq<int>)
2: {
3:    // Does not work
4:    && (forall i :: 0 <= i < |s| ==>
5:      && i is nat)
6:}
```

The error was saying for line 5: `a non-trivial type test is allowed only for reference types (got 'nat')`
which was not helpful to fix this issue.

With the fix, it is now saying `"a non-trivial type test is allowed only for reference types (tried to test if 'int' is a 'nat')"`, which indicated that the inferred type of `i` is `int`, and why it fails.

That was sufficient information for @seebees to know what the error was, add type hints at the places where it was expected and be done with the issue.
