### ISSUE TITLE
Resolver interprets name as a module instead of a type in type position

### ISSUE THREAD

**Issue by mschlaipfer** [dafny-lang/dafny#1996]
In the following example I'd have expected the `M` in `bar`'s argument `m: M` to be resolved to the `datatype M`, but Dafny gives an error. It seemingly interprets the `M` in `m: M` as the `module M`.

```dafny
module M {
  datatype M = C
}
module Foo {
  import opened M
  method bar(m: M) // error: expected type
  {

  }
}
```

I am aware that this works if I don't import as `opened` and qualify the type. It also works when I change
```dafny
import opened M
```
to 
```dafny
import opened MRenamed = M
```

I'm still wondering if the original example can be made to work.

**Comment by keyboardDrummer** [comment]
Do you know if there's a scenario in which you still want to keep the module `M` in scope after in an scope where you have `import opened M` ?

**Comment by mschlaipfer** [comment]
I am not familiar enough with the `module` system and the internal workings of the resolver, unfortunately.

**Comment by RustanLeino** [comment]
When you import a module, you get a local name for it. This is also true for `import opened`. In your example, the local name is the same as the imported module, namely `M`. So, yet another way to write your program is to declare the parameter as `m: M.M`, even if the import declaration is just `import opened M`.

An `import opened M` spills the names of `M` into the importer's scope, but these names are shadowed by any local name. That is, a local name always takes precedence over any name you get from an `import opened`. I think this behavior makes sense and is desirable.

**Comment by mschlaipfer** [comment]
I think I'd prefer not having the local name when importing opened via `import opened M`. If it is needed to resolve some name clashes one could say `import opened M = M` or `import opened RenamedM = M`. Would that be possible?

**Comment by cpitclaudel** [comment]
>    import opened RenamedM = M

This is already valid syntax, so it wouldn't be ideal to change it:

```dafny
module M {
  datatype P = P
}

module Q {
  import opened Renamed = M
  type PP = M.P // Undeclared top-level type or type parameter: M
}
```

**Comment by mschlaipfer** [comment]
I'm not suggesting your program to work. I'm proposing a way for this program to work:

```dafny
module M {
  datatype M = M
}

module Q {
  import opened M
  type T = M
}
```

When writing `import opened M`, the module `M` should not be made available as a local name in `Q`. If that behavior is desired (for resolving name clashes), I'm proposing to write `import opened M = M` to make module `M` available as a local name in `Q`.

**Comment by mschlaipfer** [comment]
The existing code is something like
```dafny
module Option {
  datatype Option<T> = Some (x: T) | None
}

module Q {
  import opened Option
  // if the argument to foo was o: Option<int> instead:
  // Wrong number of type arguments (1 instead of 0) passed to module: Option
  function foo (o: Option.Option<int>): int { // need to qualify with the module name Option here
    match o {
      case Some(x) => x
      case None => 0
    }
  }
}
```

I would argue that most programs that would be affected are programs that wouldn't be written this way in the first place if Dafny's behavior was as I suggest.

I also don't think it has to be a breaking change. I assume one could figure out if `Option` refers to a `module` or a `type` when dropping the qualifier above, but maybe I'm not aware of some difficulty?

F# allows both `Q` and `R` here:
```fsharp
module M =
    type M = int

module Q =
    open M
    let x: M = 0

module R =
    open M // Open directive is not required by the code and can be safely removed
    let x: M.M = 0
```

I find Dafny's current behavior confusing. When I open a module my mental model is that everything inside becomes available (maybe leading to name clashes which I have to fix). In Dafny everything becomes available, besides names that are equivalent to the module name.

I think there is no good way of avoiding the path qualifier, either:
  * Name the type `T` by convention, e.g. `Option.T`: need to name type arguments inside of `Option` with something other than `T` which is unusual. `opened` imports are useless as you don't want to write `T<int>`, you'd need to keep the `Option.T<int>`.
  * Rename the module to `OptionM` or so by convention

**Comment by seanmcl** [comment]
+1

**Comment by seanmcl** [comment]
> When writing import opened M, the module M should not be made available as a local name in Q. If that behavior is desired (for resolving name clashes), I'm proposing to write import opened M = M to make module M available as a local name in Q.

I think Dafny could figure out from the context whether a module or type name is required in that position. So no arbitrary aliasing is necessary.

**Comment by RustanLeino** [comment]
Rather than distinguishing `import opened M` from `import opened M = M`, I propose the following:

As a breaking change from Dafny's previous behavior, if a module `M` contains a top-level symbol with the same name, `M`, then in a client module that does `import opened M` or `import opened M = M` (that is, no renaming of the imported module) the name `M` will refer not to imported module, but will unambiguously refer to the top-level declaration inside module `M`.

I say "unambiguously", because there could be other `import opened X` declarations where `X` is some module that also declares a top-level declaration `M`. Such declarations will not be in conflict with the imported `M` from module `M`. For example, suppose `M`, `X`, and `Y` are modules, each of which declares a top-level declaration `M`. Then,

``` dafny
import opened X
import opened Y
```

will (like previously in Dafny) make `M` an ambiguous symbol in the importing module, whereas

``` dafny
import opened M
import opened X
import opened Y
```

will (new breaking-change behavior!) in the importing module make `M` unambiguously refer to the top-level declaration `M` inside module `M`.

If you like this proposal, then I have an implementation thereof.

**Comment by cpitclaudel** [comment]
With that proposal, how will one refer to other members of the module when there is a clash, as in the following case?

```
module A {
  type Y(0)
}

module X {
  type X
  type Y(0)
}

import opened A
import opened X

const aY: A.Y
const xY: X.Y
```

**Comment by cpitclaudel** [comment]
> Rather than distinguishing import opened M from import opened M = M, I propose the following:

I may be misreading the discussion above.  Did we not conclude that what was needed was a slight change to name resolution in type scope?  Types cannot have type members, so

1. the first `Option` in `Option.X` must refer to the namespace `Option`
2. `Option` on its own cannot be a module

> I also don't think it has to be a breaking change. I assume one could figure out if Option refers to a module or a type when dropping the qualifier above, but maybe I'm not aware of some difficulty?

The comments above mean that the ambiguity can be resolved in type scope, I think.  But, @mschlaipfer , what should the following program print?

```
module Opt {
  datatype Opt = Opt {
    const X := 1
  }
  const X := 2
}

module Q {
  import opened Opt
  method Main() {
    print Opt.X;
  }
}
```

**Comment by RustanLeino** [comment]
This is a good (and, indeed, perhaps better) alternative. If it's acceptable, then I'm wondering if we can take it one step further and do this regardless of if the import is `opened` or not. That is, if we see a module `A.B.C.D` in a context where we're expecting a type, then see if `A.B.C.D.D` is an accessible type, and if it is, use it.

**Comment by seanmcl** [comment]
Regarding the ambiguous example above, Scala just fails when it's ambiguous.

```
package opt;

object Opt {
  object Opt {
    val X = 1
  }
  val X = 2
}

object Main {
  import Opt._
  def run() = {
    println(Opt.X)
  }
}
```

gives

```
reference to Opt is ambiguous;
it is both defined in package opt and imported subsequently by 
import Opt._
    println(Opt.X)
```

Ocaml seems to just print the inner one, which seems like a good choice

```
# module M = struct module M = struct let x = 1 end let x = 2 end;;
module M : sig module M : sig val x : int end val x : int end
# open M;;
# M.x;;
- : int = 1
```

**Comment by cpitclaudel** [comment]
Neat, thanks @seanmcl for testing on Scala and OCaml. Both of these behavior seem reasonable, though Dafny does neither (it prints `2`).

I was partly reacting to @mschlaipfer 's comment above that "I assume one could figure out if Option refers to a module or a type when dropping the qualifier above, but maybe I'm not aware of some difficulty?": while it's (I think, mostly) unambiguous in type scope, for values things are a bit more tricky.

**Comment by mschlaipfer** [comment]
Sorry for the late reply and thanks for the example @cpitclaudel. Also thanks for trying it out @seanmcl. I think I prefer failing when there's ambiguity. That seems safer.

**Comment by cpitclaudel** [comment]
That would be a breaking change to the language, right?  That seems a bit scary to me.  We already have some precedent for it (we disallow ambiguity based on module import order), but breaking working code is something we should be careful about.

I think the source of all our issues here is that fact that when you write `import opened M` in Dafny, you get everything from `M`, and *then* `M`.  In OCaml you get `M`, and *then* everything from `M`.  Hence the default behavior in OCaml is that inner modules shadow the outer one, and in Dafny it's the reverse.

We can change this, but we'll silently change the meaning of previously working programs.  We might be able to change this *and* give explicit errors for programs that would otherwise have changed meaning.

Some litmus tests:

```
module M {
  module M {
    type T = int
    const x := 1
  }
  type T = bool
  const x := true
}

module D {
  datatype D = D {
    static const x := 1
  }
  const x := true
}

module TestM {
  import opened M
  const X: T := assert x == true; false // x is M.T.x, T is M.T
  const Y: M.M.T := assert M.M.x == 1; 1 // M.M.T is int
}

module TestD {
  import opened D
  // const X: D // Fails, could be made to work, but would be inconsistent with M.T above
  const X := assert x == true; D.D // x is D.x
  const Y := assert D.D.x == 1; D.D
}
```

One thing I like about the current behavior is that all names remain accessible.  In my own code I tend to have the following structure instead:

```
module Datatypes {
  module Options {
    type T // …
  }

  module Lists {
    type T // …
  }

  type Option = Options.T
  type List = Lists.T
}
```

It's not ideal either, because it requires all aliases to be defined at the same time.  But even without the aliases, I generally name the module `Xs` and the type `X`.

**Comment by cpitclaudel** [comment]
Updating from a recent discussion with @RustanLeino: we can proceed with allowing a type inside the module to shadow the module's name.  However, we will disallow ambiguity, instead of breaking existing code silently.  Hence, the following will be rejected:

```
module M {
  const a := 1
  datatype M = M0 {
    static const a := 2
  }
}

module Blah {
  import opened M
  method Main() {
    print M.a; // Ambiguous `a`
  }
}
```

**Comment by cpitclaudel** [comment]
Implementing the change above turned out to me much more involved that I had hoped, because it morally involves running two resolutions, one with and one without the shadowing of the module's name, but I think the implementation is mostly complete.  I updated the corresponding pull request directly (https://github.com/dafny-lang/dafny/pull/2355).  The gory details are there.
