### ISSUE TITLE
Having trouble applying lemma involving bit-vectors

### ISSUE THREAD

**Issue by VictorYYW** [dafny-lang/dafny#2230]
The following snippet cannot be verified.
```dafny
lemma MergeLShift(v: bv128, i: nat, j: nat)
  requires i <= 128 && j <= 128 && i + j <= 128
  ensures v << i << j == v << i + j

method M(i: nat)
  requires i <= 64
{
  ghost var half: bv128 := 0xffff_ffff_ffff_ffff;
  MergeLShift(half, 64, 64 - i);
  assert half << 64 - i << 64 == half << (128 - i);
}
```
Changing `nat`s to `bv32` would make it work, reminding me of #2174. 

It seems Dafny is having problem with `64-i`. For example, this lemma is inconclusive as well. Again, changing `nat`s to `bv32` works.
```dafny
lemma whyyy(v: bv128, a: nat, b: nat, i: nat)
  requires a <= 64 && b <= 64 && a == 64 - i
  ensures ((v << 64 - i) << b) == ((v << a) << b)
{}
```
On a separate note, no matter with `nat` or `bv32`, lemma `MergeLShift` itself is inconclusive.

**Comment by atomb** [comment]
As one data point: if I change `MergeLShift` to use `<` instead of `<=`, and use `bv` types for `i` and `j`, it goes through for me.

**Comment by VictorYYW** [comment]
Interesting. Just for record's sake.
```dafny
lemma MergeLShift(v: bv128, i: bv32, j: bv32)
  requires i < 128 && j < 128 && i + j <= 128
  ensures v << i << j == v << i + j


method M(i: bv32)
  requires i <= 64
{
  ghost var half: bv128 := 0xffff_ffff_ffff_ffff;
  MergeLShift(half, 64, 64 - i);
  assert half << 64 - i << 64 == half << (128 - i);
}
```
goes through.

**Comment by atomb** [comment]
Ah, good to know! So it's just the individual `i` and `j` that need to be `< 128`, not `i + j`.

I'm now curious about the precise semantics of `<<` in Dafny for RHS values greater than or equal to the bit width of the LHS.

Besides that subtlety, the rest seems unsurprising to me, since it's all in terms of bit vectors, so the verification problem should be relatively easy. Reasoning about the relationship between bit vectors and integers (or naturals) is where things tend to get tricky.

**Comment by atomb** [comment]
Oh, I'm wrong about the `<`. The following works. The version with `bv8` didn't work just because the addition might overflow, so at least one of `i` or `j` needed to be strictly less than 128.

```dafny
lemma MergeLShift(v: bv128, i: bv16, j: bv16)
  requires i <= 128 && j <= 128 && i + j <= 128
  ensures v << i << j == v << i + j
  {}
```

**Comment by VictorYYW** [comment]
> I'm now curious about the precise semantics of `<<` in Dafny for RHS values greater than or equal to the bit width of the LHS.

I believe the RHS is not allowed to exceed the bit width of the LHS.

> so at least one of `i` or `j` needed to be strictly less than 128.

Probably it has something to with the chaining of two `<<`s.

**Comment by atomb** [comment]
The interesting thing is that Dafny accepts this (leaving the commented-out line commented out):

```dafny
method M() {
  var x: bv32 := 1;
  var y := x << 16 << 16;
  var z := x << 32 << 32;
  var w := x << 32;
  // var u := x << 33; // Leads to error
  assert y == 0;
  assert z == 0;
  assert w == 0;
}
```

So, when chaining `<<`, each RHS has to be less than _or equal to_ the bit width, but the sum can _exceed_ it. And, for a single `<<`, the RHS can be equal to the bit width.

**Comment by atomb** [comment]
After deeper inspection, I think I know what's going on here, and in #2174 and #2199. The expression `v << i` where `v` is a bit vector (say `bv64`) and `i` is a `nat` involves an explicit cast of `i` to a bit vector of the same size as `v`: `i as bv64`. If the width of `v` is large, the space the solver needs to explore is large.

If, on the other hand, `i` is a small bit vector, Dafny casts it to a large bit vector by zero-extending it. In this case, the solver doesn't need to explore as large a space because it knows that most of the bits of the shift amount are zero.

So, the key thing we need to do is replace the current behavior,`v << i` -> `v << i as bv64`, with a slightly different behavior, `v << i` -> `v << (i as bvA) as bvB` where `bvA` is the smallest bit vector that can store the range of `i` and `bvB` is the type of `v`.

The tricky part here is determining the range of `i` predictably. In many simple cases, it'll be readily available, syntactically, but it would be very brittle to take advantage of that.
