### ISSUE TITLE
Dafny 4.0 suggestion: `opaque` keyword

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#2337]
To have consistency with the language, I suggest to introduce the keyword `opaque` as an alternative to `{:opaque}`

`function {:opaque} f(): int { 1 }`
becomes
`opaque function f(): int { 1 }`

`method{:opaque} m() returns (j: int) { j := 1 }`
becomes
`opaque method m() returns (j: int) { j := 1 }`

Support for multiple 
```dafny
export F
  extends M
  provides X, Y
  reveals W, U
```
could become
```dafny
export F
  extends M
  provides opaque X, Y
  provides W, U
```

```
newtype int32 = x: int | -0x8000_0000 <= x < 0x8000_0000
```
could become
```
opaque type int32 = x: int | -0x8000_0000 <= x < 0x8000_0000
```
(however, this might have the side effect that an int32 is always an int and can be assigned to an int, which we might not want)

If a definition is `opaque`, then it can always be revealed in client code, otherwise, we can keep `export reveals` to automatically reveal opaque client things, but I'm not sure it's a good idea to keep it

**Comment by robin-aws** [comment]
> `method{:opaque} m() returns (j: int) { j := 1 }`

Intended this after "becomes" perhaps? :)

`opaque method m() returns (j: int) { j := 1 }`

**Comment by MikaelMayer** [comment]
Fixed!

**Comment by robin-aws** [comment]
Adding this to the Dafny 4.0 milestone as I know @RustanLeino feels strongly about it.

**Comment by keyboardDrummer** [comment]
@MikaelMayer Did you intend

```
export F
  extends M
  provides opaque X, Y
  provides Y, Z
```

to be this?

```
export F
  extends M
  provides opaque X, Y
  provides W, U 
```


Also, could help me understand what's opaque about a newtype?

**Comment by MikaelMayer** [comment]
Thanks, I fixed my example.

I might be wrong, but to me it feels like newtypes are trying to encode what I think an "opaque subset type" would be.
Maybe the bigger difference is the following. With a subset type with an opaque constraint, it is still compatible with the base type, whereas a newtype defines a wholly new type and hides the base type, correct?

**Comment by keyboardDrummer** [comment]
> Thanks, I fixed my example.
> 
> I might be wrong, but to me it feels like newtypes are trying to encode what I think an "opaque subset type" would be. Maybe the bigger difference is the following. With a subset type with an opaque constraint, it is still compatible with the base type, whereas a newtype defines a wholly new type and hides the base type, correct?

Makes sense, thanks.

**Comment by RustanLeino** [comment]
I like the `opaque` modifier for functions (and predicates). An opaque function can then be `reveal`ed to make its definition usable and known to clients.

This Issue also proposes changes to things that an export set `provides` and to `newtype` declarations. These are not like opaque functions, because they cannot be `reveal`ed. Therefore, I'm not in support of those two parts of the proposal.

In more detail:

Today, if a function is placed in a `provides` clause of an export set, then there is no way for a client to obtain the body of that function. The body remains private to the module. If the function is instead placed in a `reveals` clause, then its body is available to all importers. As a hybrid, if you declare a function to be opaque and place it in a `reveals` clause, then clients get to find out about the function (like just with `provides`) and have the option of obtaining its body by using a `reveal` statement.

For a `newtype` today, all clients immediately get to know the base type and constraint of the definition. There is no `reveal` operation on such a type. Therefore, I don't think a `newtype` is an `opaque type`. Rather, it's more like a "standalone" subset type or type synonym.

**Comment by MikaelMayer** [comment]
Thanks for your analysis. Makes sense. Although I'm still not entirely satisfied with the range of concepts we are serving at once.

**Comment by MikaelMayer** [comment]
Perhaps we could have "export interface" and "export implementation" instead of "export provides" and "export reveals"? That way, it's obvious the body is or is not provided.

**Comment by MikaelMayer** [comment]
Ok, for now, let's just focus on the `opaque` keyword for functions, methods and predicates, I suggest we keep it like "least" so that it can still be used as an identifier in contexts where it's not necessary as a keyword.

**Comment by MikaelMayer** [comment]
Course of action:

* Enable the "opaque" keyword to be used before functions, predicates, methods and constants
* Add an option -opaqueSyntax:3 or 4, with value 3 by default, like we did for "functionSyntax"
* Add a warning for the {:opaque} user-supplied attribute that is activated only with -opaqueSyntax:4
* Convert the user-supplied "opaque" keyword to an implicitly generated attribute ":opaque" for compatibility

**Comment by jtristan** [comment]
What about least/greatest/twostate predicates? Would we have to say "opaque least foo" or "least opaque foo" or maybe both? I agree that we should replace the use of the opaque attribute, but is there a more lightweight notation we could use?
For example, for requires, I like that you can make them opaque by naming them, as in:
"requires H: P"
It also makes me wonder if it might make sense to have the caller decide whether or not a function/predicate should be opaque rather than the callee.

**Comment by MikaelMayer** [comment]
> Would we have to say "opaque least foo" or "least opaque foo"

Here is my humble opinion.
"opaque least predicate foo" is the most appropriate. Because "least" is not an adjective and binds stronger in the English grammar than an adjective, putting it in front of "opaque" would transform the meaning: "least opaque predicate" would mean "predicate that is the least opaque", very different.

We could also support both and use a linter to suggest the first.

Assertions and requires are not named by default, so this can explain why giving them a name can be associated to making them opaque. But functions and predicates already have names, so I think a keyword is more justified than assigning a double name.

For the last part, you have a point. I would make sense if the callee could treat a function as opaque, I agree that it would many times save the day where we don't want to put a predicate opaque by default, but only at the call site when needed (i.e. because we want to optimize verification).
We could encode this in Boogie by making all functions and predicate opaque by default and reveal them at the call site unless they are explicitly hidden.
A lot of things to consider then, such as

* Could we make it a non-breaking change? i.e. have an attribute {:automatically-revealed} on opaque functions, and introduce ways to make function calls opaque.
* How to write an opaque function call? Opaque keyword? special syntax between function and the arguments?

**Comment by kjx** [comment]
If you get a good syntax for annotations then this problem goes away - every "attribute" turns into a "modifier", some of which are more special than others.

The big one for me is of course `autocontracts` - although well, perhaps `contracted` or `contract` (or `bertrand`)  is a better name for it.  


 - https://github.com/dafny-lang/dafny/issues/2455#issuecomment-1409837026 -

**Comment by davidcok** [comment]
opaque implemented for const and all kinds of functions. Methods cannot be opaque -- or actually always are.

Until Dafny 4, opaque is also allowed as an identifier, but deprecated.  Implemented in PR3462

**Comment by kjx** [comment]
Ha! for what it's worth, I came up with an argument why `opaque` should *not* be an unquoted "identifier". Semantically, `opaque` is a modifier;  a hint or rather a directive to the solver, but it shouldn't change the propositional meaning of a dafny program.
the analogy with Prolog's cut should be clear.

on the other hand - something like `auto contracts` - well as far as I can tell
only `auto contracts`  *does* change the core semantics of the program...

**Comment by kjx** [comment]
(mostly unrelated question - should this be a new issue or on stack exchange or?)

if wanted to implement a modified like auto contracts, 
would that age a dafny plugin?
where are pluggins documented? only in the code?
