### ISSUE TITLE
Dafny 4.0 suggestion: get modern assignment operators

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#2345]
I know it will probably not make it, but since I had the idea, let me throw it here.

The assignment operator `:=` is used in what I would call ["old languages" and "mathematical languages"](http://rigaux.org/language-study/syntax-across-languages.html#VrsVrbssgOrDcl)
We could lower the barrier to entry for users if we got used to a modern assignment operator used by the top 10 programming languages in the world `=` (except R which uses `<-`), which saves one character, and will later make it possible to use condensed versions everyone affectionate like `+=`.
All built-in assignment operators could start with "=" as a prefix:

| Old syntax | Suggested syntax |
|-------------|--------------|
| `myVar := 1;`       | `myVar = 1;`         |
| `this.property := 1;`       | `this.property = 1;`         |
| `var localVar := 1;`       | `var localVar = 1;`         |
| `var i, j, k := method_call();`       | `var i, j, k = method_call();`         |
| `maybeVar :- Compute();`       | `maybeVar =? Compute()`         |
| `:- Need();`       | `=? Need()`   or  `=- Need()`|
| `var x :\| p(x);`       | `var x =\| p(x);`        |
| `if x :\| p(x) { ... }`       | `if x =\| p(x) { ... }`        |

**Comment by cpitclaudel** [comment]
😱

**Comment by robin-aws** [comment]
> 😱

Sometimes an emoji is worth a thousand words? :)

In all seriousness, Dafny uses `:=` and `==` to be very clear about the difference between assignment and equality, and explicitly avoids `=` because it has been historically confusing and error-prone.

Even if the suggestions were obviously much better, this would be a lot of pain for existing codebases to have to switch, so they would have to be a LOT better to make it worth it.

At least for the last two there is this alternative to `:|` we can consider: https://github.com/dafny-lang/dafny/issues/2340

**Comment by MikaelMayer** [comment]
It almost feels like I want to drive to the left side of the road in the US ^^.

The confusion between `=` and `==` historically happened only in languages which accepts the assignment operator as an expression, e.g. in PHP, Javascript... `while(x = 1) { x = 0 }` that loops indefinitely. In Dafny, this would simply be not possible. Assignments are statements, you can't mistake them for expressions. The only way to embed statements in expressions is through the var binding, assertions, assumes, expects, and lemma calls.
So there is no actual error we prevent by distinguishing `:=` from `=` that I am aware of.

Moreover, we are only modifying the state when we assign fields, because when we are simply re-assigning local variables, it does not need a `modifies` clause.

**Comment by robin-aws** [comment]
Very true, the hard-line distinction between statements and expressions in Dafny makes `=` much less dangerous.

I'd only be convinced this is worth it if we feel strongly this would help with Dafny adoption by new users, enough to justify the migration cost for existing users. And I'm not yet convinced this syntax issue is enough of a pain point, especially compared to needing to think about and structure code differently in order to verify it.

**Comment by MikaelMayer** [comment]
That's a good point. Would you like me to run a survey to ask about this point for our users?

Here are the pain points I can feel:
- We cannot currently envision the operator `+=` in Dafny, but it's one of these operators used everywhere. Should we design `+:=` ? Nah that looks ugly. So we'll keep duplicating the variables names (`object.field := object.field + 1`). I know it "feels good for reasoning", but Dafny at some point will provide "automated reasoning tools" so that [verification debugging](https://dafny.org/dafny/DafnyRef/DafnyRef#sec-verification-debugging) wouldn't care of the syntactic sugar.
- People writing different programming languages (such as me), for example when having a core Dafny file to integrate into another project, frequently use the wrong assignment operator when switching languages, all the time. It's like trying to switch from a QWERTZ keyboard to AZERTY all the time. It can be exhausting.

**Comment by kjx** [comment]
FWIW I really don't think this is a big problem (and strongly prefer ":=" to "=" for assignment for the reasons robin gives above --- especially as Dafny's keeps the statement/expression distinction common to Wirthian ":=" languages. 

I'd love to help with fixing up Dafny's syntax - but for me, this isn't even in the top ten actual problems. 
(var/const; if/then?;  semicolons; forall/&&; decreases/bodies; returns/":"; map[x := y]; seq comprehensions;
Rust pretty printing of inductive types; ordering vs sorting; abstracting collections; stateless objects;
Alloy's "sum" quantifier; autocontracts; ...)  I'm sure there are more!

**Comment by MikaelMayer** [comment]
Closing as not pursued
