### ISSUE TITLE
Organization of Dafny user-facing material

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#2378]
Currently there are these disparate locations of Dafny information:

a) The single "Github pages" web page in Dafny-lang/dafny-lang.github.io, which is shown at Dafny.org
b) The tree of documentation in dafny-lang/dafny/docs, which is mounted by the main Dafny project settings at Dafny.org/dafny.
This holds the reference manual and various lists of resources.
c) The Dafny project README page
d) The Dafny project wiki (setup, tips & tricks, how to contribute as a developer)

- The organization of the Dafny.org information is unusual: should the documentation tree be moved into dafny-lang.github.io?
- There is duplication of information that should be cleaned up and unified.

- A user might justifiably be confused about where to look for information: wiki vs. GitHub pages (though links from GitHub.io pages to wiki pages can certainly be added

- And should we have a separation between user information and Dafny developer information?

Open for comment before any plan is developed. Particularly any info on decisions that led to the current state would be welcome.

**Comment by robin-aws** [comment]
> The organization of the Dafny.org information is unusual: should the documentation tree be moved into dafny-lang.github.io?

I strongly prefer being able to modify the implementation and documentation atomically in a single PR. However, we should be much more clear that the content on `dafny.org/dafny` is built from master rather than any particular release of Dafny.

I say we should have multiple snapshots/builds of the documentation available: one for the latest state in `master`, and one for each Dafny release (at least the most recent when we make this change, and maintaining older ones as new versions are released). The latest can change on every merged PR, and the copies corresponding to releases should be created as part of the release process somehow. 

That may mean we render the latest directly from `dafny-lang/dafny` and store snapshots in `dafny-lang.github.io`. I'm open to suggestion on the exact strategy, as long as we can have GitHub actions to automate whatever has to be done when releasing.

> There is duplication of information that should be cleaned up and unified.

Agreed, and feel free to take on some of the obvious duplication! :)

> A user might justifiably be confused about where to look for information: wiki vs. GitHub pages (though links from GitHub.io pages to wiki pages can certainly be added

FWIW, I prefer to move away from using the wiki for core documentation purposes, mainly because it is not versioned together with the actual implementation, and doesn't support the same PR workflow. 

> And should we have a separation between user information and Dafny developer information?

Absolutely! At the moment the primary developer-focused documentation is in one of these locations, and it would be nice to centralize:

* https://github.com/dafny-lang/dafny/blob/master/.github/CONTRIBUTING.md
* https://github.com/dafny-lang/dafny/wiki#developing-the-dafny-tool
* https://github.com/dafny-lang/dafny/tree/master/docs/Compilation (arguably user-facing for more advanced users)

**Comment by cpitclaudel** [comment]
> That may mean we render the latest directly from dafny-lang/dafny and store snapshots in dafny-lang.github.io. I'm open to suggestion on the exact strategy, as long as we can have GitHub actions to automate whatever has to be done when releasing.

I would love that.  We could have CI push to dafny-lang.github.io

**Comment by fabiomadge** [comment]
The current dafny.org is the result of me wanting to have a more permanent place to point people to and also giving users a way to reach us by mail (security@dafny.org, ...), while not spending more time on building it than strictly necessary. It would be great, if we could make a plan and execute it to move more content there. We have also often talked about putting blog posts there.

**Comment by davidcok** [comment]
To be clearer. Aside from the single fairly static page at dafny.org, all documentation (except what is on the wiki) is in the main GitHub project, is subject to version control and the PR process and thus you can have an atomic implementation and reman change. Furthermore, currently a pdf build of the RM (current as of the release) is built and packaged with each release. All of that appears (given Robin's comment) to be desired and not to change.

The Dafny.org/dafny web pages are all current as of the most recent push on master, so they are bleeding edge documentation. If that is not desired then we need to disconnect the current dafny/docs tree from GitHub pages and push a duplicate of Dafny/docs to Dafny-lang.github.io when each release is created.

I see a number of alternatives:

1) Move Dafny.docs to dafny-lang.github.io. This goes against a number of Robin's workflow points, though it is a typical organization to use if GitHub pages are used. (It used to be the only option, but now one can set, for example, dafny.org to point to some other spot in your project, as we do now for dafny.org/dafny)

2) Move Dafny-lang.github.io into dafny/docs and get rid of Dafny-lang.github.io but preserve the link between Dafny.org and the user documentation. This would in essence revert Fabio's change, but we would be sure that the information at Dafny.org pointed users to all the relevant documentation/issues lists/discussion forums etc. This is my preference -- it keeps everything under one repo and uses GitHub tools and processes, while uniting all of the user documentation in one place.

3) Make the docs under dafny-lang.github.io a duplicate of dafny/docs as of the most recent release. If having Dafny.org be release-based instead of bleeding edge documentation, this could work. However, one then needs to view the current status with a local server, which is a nuisance, and then one can't push documentation corrections and enhancements (all those TODOs) independent of releases. So this is not my preference.

4) More or less status quo. (I would at least add more links onto the Dafny.org page).

**Comment by fabiomadge** [comment]
To provide a little more background. I think we should have something at the root of dafny.org and the repo I set up is the only way I know of to achieve that. The whole dafny.org/dafny thing is also hardcoded by the repo name if the main repo.

**Comment by fabiomadge** [comment]
I think that we should target stable with our documentations, as this is what we expect users to live on. Incentivising us to do more frequent releases is a good thing in my book.

**Comment by davidcok** [comment]
> To provide a little more background: I think we should have something at the root of dafny.org 

Agree completely.

> and the repo I set up is the only way I know of to achieve that. The whole dafny.org/dafny thing is also hardcoded by the repo name of the main repo.

No, you can have something at the root of dafny.org within the main repo without the dafny-lang.github.io repo -- at least I believe that is what we had 2 years ago.

> I think that we should target the latest release with our documentation

If there is general agreement on that, I'll make it a task of mine to construct that document organization and release workflow (that is, alternative 3 above).

**Comment by robin-aws** [comment]
(Adding `breaking-change` only because this would be very good to address before releasing Dafny 4.0, as we should make it very easy to find the complete snapshot of documentation for Dafny 3.X)

**Comment by davidcok** [comment]
Here is my proposed organization and workflow for the user-facing documentation:
There are two design goals:
- commits to the docs should be atomic with commits to code, which argues for having the docs in the same repo (dafny-lang/dafny.git)
- revisions to user-facing docs should be made public along with a new release (and edits between releases should not be made public, unless it is an emergency "bug fix" to a release)

So the design is:
- Have all the docs in the main dafny repo (where they mostly are now, under the docs folder). Developers would edit them along with code and review and push them to master as part of the current workflow.
- The docs would be served to the public from a dedicated branch, say 'public-docs' and be visible at dafny.org
- As part of the release process, current master would be merged into public-docs and public-docs would be pushed to the server (just a git push); public-docs would be tagged to indicate the release.
- The Dafny team would adopt the policy that user-facing docs are in the dafny repo and subject to source control and standard PR review; developer-facing docs can be in the wiki, without the usual PR review. As part of implementing this design, some content (how-tos, pitfalls) in the wiki would be moved to the user docs.
- Emergency fixes to public-docs could be made by creating a bug-fix branch, fixing the problem and merging/pushing it to the server
- The dafny-lang.github.io repo would be no longer needed. This design also does not need duplicate copies of docs -- one in the dafny-lang.github.io repo and one in the dafny.git repo, which would have the danger of becoming out of synch.

Note that this design is feasible because it is now possible to serve GitHub pages from any repo and any branch (it used to be constrained to ...github.io repos and gh-pages or master branches, at least as far as I knew).

**Comment by fabiomadge** [comment]
I still don't think that it's possible to publish from `dafny-lang/dafny` to dafny.org. Maybe we could try it with a different organisation. 
How does that work for still delivering old versions? I would like to see something like dafny.org/manual/latest and dafny.org/manual/v3.7.3.
I would prefer moving all content away from GitHub and to that new website.
I don't expect us to have doc emergencies.

**Comment by davidcok** [comment]
@fabiomadge - we currently publish from dafny-lang/dafny/docs to dafny.org/dafny. And I have no trouble previewing from any repo and branch. Are you concerned that we can't publish to the top-level? If you are correct, we can then retain the one landing page in dafny-lang.github.io and have everything else dafny-lang/dafny -- as it is right now -- but still use a public-docs branch.

Delivering old versions to the public was not expressed as a goal. If it is, then we can copy a snapshot to an appropriate URL without trouble as part of the release process. Other opinions?

Note that the "new website" is still GitHub, just a different repo. One of the goals was to keep stuff in one repo. I don't think a second repo gives any benefits.

**Comment by fabiomadge** [comment]
I'm sill open to be convinced of the feasibility of publishing from dafny-lang/dafny to dafny.org. I would prefer avoiding to pollute most of our URLs with an extra `dafny`.  This is why I created the repo in the first place, as discussed before.
Dafny.org being hosted on GH is just an implementation detail and we still own the whole experience. This is not true for anything under GitHub.com, like wikis.

**Comment by cpitclaudel** [comment]
The design I'm used to is that the *sources* of the docs are in the main repo (so for us dafny-lang/dafny), and *builds* of the docs are generated and pushed out by CI.  Usually this involves committing a snapshot of the documentation to a separate repo (which in our case could be dafny-lang.github.io).  This makes it trivial to keep older revisions of the docs available.

**Comment by davidcok** [comment]
IN this case though the builds are done behind the scenes by GitHub Pages, so we never see the html that is produced. There are no generated files (except I guess the .pdf that will be going away)

**Comment by robin-aws** [comment]
I'm not a fan of the same-repo `public-docs` branch approach because it abuses the notion of branches IMO: that branch will permanently hold divergent content, and the diff when pushing from mainline ends up meaningless and pointless to review. It also can't naturally maintain older versions.

I'd prefer pushing snapshots to a separate new `manual/<version>` subdirectory on the `dafny-lang/dafny-lang.github.io` repo during each release. We should be able to serve the latest out of mainline `dafny-lang/dafny` directly as we are now AFAICT, with clear indications that the content is for bleeding-edge unreleased Dafny. Or perhaps we could push to `dafny-lang.github.io/manual/nightly` in the nightly build?

I wonder if we could use something like https://readthedocs.org/ in the future instead to host the released snapshots of documentation in the future. That platform is specifically designed to host multiple versions of fully-built documentation.

**Comment by davidcok** [comment]
OK. This approach then:

- current docs under /docs, as before
- and then /docs/asreleased/current, /docs/asreleased/v3.7.1, etc.
- with web pages being served out of /docs/asreleased/current and a list somewhere with links to older docs

My gut feel says there will be next to no demand for older docs online

**Comment by richardlford** [comment]
> except I guess the .pdf that will be going away

Do you mean there are plans to no longer produce a pdf? I personally like to have pdf versions, e.g. so that I can have a printed copy.

**Comment by davidcok** [comment]
It is part of each release, but the bleeding edge build of the pdf has not been happening for some time.

**Comment by robin-aws** [comment]
> * current docs under /docs, as before

I'd prefer the bleeding edge state be at a more explicit path as well, if possible. If we're going to have multiple versions available at all (which I think we agree on, since at a minimum we want to have both bleeding edge and last release versions) I don't think we should have any default unqualified path.

> * and then /docs/asreleased/current, /docs/asreleased/v3.7.1, etc.
> * with web pages being served out of /docs/asreleased/current and a list somewhere with links to older docs

Sounds good to me! We can bikeshed a bit more on the exact paths. :)

> My gut feel says there will be next to no demand for older docs online

I expect there will be as adoption grows and we have more users maintaining codebases that are sitting on older versions. Especially since we'll want to update tons of examples to use the new function syntax for Dafny 4.0, and developers on codebases that haven't upgraded yet will get very confused if they don't have a 3.X copy of the documentation handy.

**Comment by davidcok** [comment]
Based on feedback above, this is the design I'm aiming for. It is premised on these points:
- the desire to have atomic commits of code and documentation changes -- which means having current documentation files in the dafny-lang/dafny repo
- the desire to not have the redundant 'dafny' in documentation URLs
- the desire to have dafny.org link to the documentation as of the latest release
- the desire to have the snapshots of past versions also available through additional URL links
- the desire to have the current (bleeding edge documentation) also available to users, but not as the default.
The last three points will definitely take additional infrastructure, so if you think they are not or definitely are needed, please speak up now.

I have not decided whether it is better to maintain the snapshots of documentation (for each release) in the dafny-lang/dafny repo or the dafny-lang/dafny-lang.github.io repo. The former has the advantage of everything in one repo; the latter is probably simpler and less change from the present structure. Both would require release-time automation.

**Comment by robin-aws** [comment]
I would prefer the latter, and we can make it clear that we are using `dafny-lang.github.io` as a write-only repository to host snapshots of past versions of content. In the long term we could even replace the GitHub Pages hosting of this content with something more fit to purpose such as readthedocs.org.

**Comment by davidcok** [comment]
Completed by PR 2798
