### ISSUE TITLE
Dafny 4.0 suggestion: `modify X {}` should become `modifies X {}`

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#2425]
The modify statement has two forms:

modify frame-expression; -- this havocs the fields of the given expressions

modify { frame-expression } { statements } -- in this case the 'modify' is actually a 'modifies' clause whose scope is the succeeding block statement. The description in the RM even calls it a modifies clause.

Given that 'modifies' is also a keyword, I think that the second form is misnamed and confusing. It ought to use the keyword 'modifies'. 

I suggest that 'modifies' be permitted in this place, that this second form be, grammatically, a form of a block statement rather than a modify statement, and that 'modify in this second form eventually  be deprecated.

**Comment by MikaelMayer** [comment]
I wholeheartedly agree as myself I found it confusing. I renamed the title of this issue to specify it could be a change to integrate in Dafny 4, since it's a breaking change.

**Comment by robin-aws** [comment]
I'm definitely game for this, and the migration is so simple I think it's reasonable to just drop `modify` in Dafny 4.0. We can still recognize `modify` but reject it with a clear error message.

**Comment by RustanLeino** [comment]
(First some general comments, then my overall thought on the matter.)

The `modify` statement was introduced for one purpose, which was to allow a refinement module to modify some previously declared state (see http://leino.science/papers/krml248.pdf). The idea is that an abstract module writes `modify W;`, and that a refinement module thereof makes the statement more concrete by writing `modify ... { S }`. Since the token `...` is used to stand for the original `W`, the statement also permits the statement `modify W { S }`.

The keyword `modify` for the statement goes with the specification that says that a method `modifies` something. This is analogous with `return` and `returns`, and with `yield` and `yields`.

The syntax of `modify` could be improved using the keyword `by` when a body is present. Not only would that make it read better, but it would also make it look more like `assert P by { S }`, which was introduced much after the `modify` statement. To me, it seems fine to have the statements `assert P;` and `assert P by { S }` -- that is, there seems to be no reason to make the latter `asserts P by { S }` or `ensures P by { S }`.

We have received some request for a more general statement with specification clauses, like the block specification in VCC. Such a statement could, like @davidcok proposes above, have a `modifies` clause. I'm sympathetic to such a block statement, but it would be nice for it to be motivated by strong use cases. For consistency with other statements, I think it should then probably also start with another keyword. For example,

```
do
  requires Pre
  modifies W
  ensures Post
{
  S
}
```

My overall thought is that `modify` is rarely, if ever, used. The only reason for using it is with the statement-level superposition refinement that Dafny allows (see the paper I linked above). Those features have had very low payback (except in `Test/dafny1/SchorrWaite-stages.dfy`, where they work out beautifully). I think it would be prudent to remove all statement-level superposition refinement features in Dafny (essentially, the elision statement `...;`, the `modify` statement, and the forms of statements that allow a `...`). Other than the `SchorrWaite-stages.dfy` program, I don't know of any good uses of these features, and they are costly for us to maintain. Therefore, I suggest we make the use of these features generate a deprecation warning, and that we then remove those features a few minor versions later, unless we hear complaints.

(I'm not suggesting, at this time, that we remove the declaration-level refinement features (e.g., `method M...`).)

**Comment by robin-aws** [comment]
(Note from discussion: statement-level refinement may be marked as deprecated in Dafny 4.0.)

**Comment by davidcok** [comment]
I have an outstanding task to document (in the RM) the statement level refinement features in Dafny.
Instead I will document them as deprecated and ultimately remove them from the RM.

**Comment by davidcok** [comment]
Regarding modify/modifies, assert/ asserts etc. I think there is a semantic difference between the elements of these pairs.  A word like modify, assert, assume is an action verb, an instruction to do something. On the other hand, the words modifies, asserts, assumes, requires, ensures are descriptive, a property of something. Thus the latter are appropriate for specifications --- they describe what the method does; the former are good for statements --- they state an action to be taken. So I don't think the members of these pairs are interchangeable.

But I'm happy with the idea that `modify X { }` should become `do requires ... modifies ... ensures ... by { }` if we ever introduce statement level specifications.

**Comment by RustanLeino** [comment]
Given some recent discussions and comments on https://github.com/dafny-lang/dafny/pull/2756 (@davidcok , @MikaelMayer ), we are deprecating all statement-level refinements. This includes any `...` occurring in a `modify` statement.

Although a `do requires /*...*/ modifies /*...*/ ensures /*...*/ { /* ... */ }` statement has some support, I suggest we don't introduce such statement until there's a pressing need for it.

In the meantime, we are are left with two forms of the `modify` statement:

``` dafny
modify X;
modify X { /*...*/ }
```

I suggest we change the syntax of the second form to be

``` dafny
modify X by { /*...*/ }
```

This would make it have the same syntactic structure as the `assert` statement. (Alternatively, we could deprecate the second form.)

**Comment by davidcok** [comment]
I vote for deprecating the second form, in favor of a more complete solution for block-level specifications, if there is sufficient user need. The first (havoc) form would remain.

**Comment by davidcok** [comment]
Off-line agreed to deprecate the second form.

**Comment by davidcok** [comment]
This Issue is completed except for the possibility of introducing statement-level specs in the future. That aspect is captured in a new issue #2811
