### ISSUE TITLE
Move missing semicolon error above

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#2507]
I have this issue constantly. For example:
```dafny
method Test(i: int) {
  assert i >= 0

  var j := 2;
}
```
Dafny's error is unhelpful:
![image](https://user-images.githubusercontent.com/3601079/181540500-dd7e66c8-ce73-4e7a-bb16-296ffc08c900.png)

* First, it indicates the error on the wrong line. It should be two lines up.
* Second, instead of saying "invalid AssertStmt", it should say "Missing semicolon".

**Comment by davidcok** [comment]
I would expand this issue. There are many common syntactical errors for which the generated grammar produces unhelpful messages. A bit of enhancement of the grammar to catch these is straightforward. Besides missing semicolon, there is extraneous semicolon, using `=` instead of `:=`, an initializer for a field, misspelled keyword, (or for Java/C veterans, putting type before name in declarations :-).

One typically gets a 'closeparen expected' or 'right brace expected' or an error at the beginning of the subsequent statement or clause. It is a bit heuristic as to which of these is worth catching, but it certainly would help new users.
