### ISSUE TITLE
Non-Zero exit code on failing test with `/runAllTests`

### ISSUE THREAD

**Issue by DavePearce** [dafny-lang/dafny#2513]
At the moment, `dafny /runAllTests:1 ...` does not produce a non-zero exit code when one of the tests actually fails.  That means test failures cannot be automatically picked up by build tools (e.g. `gradle`) or other CI runners.

**Comment by robin-aws** [comment]
I was very displeased with this at the time as well. :( Unfortunately the deeper reason is that Dafny main methods don't allow any return values, so I couldn't generate a main method that did. Hence printing out `Test failures occurred: see above.` in lieu of a non-zero exit code, so at least there is something easy to grep for.

https://github.com/dafny-lang/dafny/issues/1116 tracks this deeper issue, which I would love to address sooner rather than later.

**Comment by DavePearce** [comment]
Hi Robin, thanks for the comments!  Ok, we can close this then.  Thanks for the pointer :)
