### ISSUE TITLE
Dafny 4.0 suggestion: default to /definiteAssignment:3

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#2728]
This is arguably what most programmers would expect. I was quite surprised to learn this wasn't the default behaviour when I first learned Dafny, and I strongly recommend every Dafny project includes this flag unless it has a very good reason not to.

**Comment by cpitclaudel** [comment]
`/definiteAssignment:3` rejects the following code:

```dafny
method M(s: set<int>)
  requires s != {}
{
  var x :| x in s;
  print x;
}
```

Maybe we want `/definiteAssignment:2`?

**Comment by robin-aws** [comment]
I'd definitely be happier with `2` as the default rather than `1`, at least. :)

I do still like the idea of guaranteeing Dafny programs are fully deterministic by default, but more willing to be convinced that's too aggressive.

**Comment by keyboardDrummer** [comment]
The new CLI UI defaults to a relaxed version of `/definiteAssignment:2`, with the option of going to `/definiteAsignment:3` using `--enforce-determinism`. Setting the latter by default doesn't seem great because it prevents creating uninitialised arrays which is done commonly.

I think we could make `--enforce-determinism` the default only if we make it performant and easier to initial arrays, which currently requires passing an array initialiser function, or if we enable tracking the definite assignment of individual array values, but that seems to be a non-trivial verification task (https://github.com/dafny-lang/dafny/issues/3232#issuecomment-1401115640).
