### ISSUE TITLE
Ambiguous reference to type in module when names are equal, when importing as opened

### ISSUE THREAD

**Issue by mschlaipfer** [dafny-lang/dafny#274]
In the following example, there's an ambiguous reference to `M.M` in module `N2` even when fully qualifying its path. When not importing `M` as opened (as in `N1`) there is no error.
The same is true for any type definition (like class or trait definitions).
When the name of the module (`M`) and the type inside (`M2`) are not equivalent, all is fine.

```
module M {
    //trait M {}
    //class M {}
    type M
    trait M2 {}
}

module N1 {
    import M
    trait T {
        var m: M.M
        var m2: M.M2
    }
}

module N2 {
    import opened M
    trait T {
        var m: M.M
        var m2: M2
    }
}
```

**Comment by davidcok** [comment]
Fixed by implementing the rule that local declarations in a module take precedence over imported names, and a 'import' statement is a local declaration of a alias for the module being imported. So here M as the import name for module M takes precedence over the import of type M.M as M (in the import opened).

Fixed in PR946
