### ISSUE TITLE
Soundness bug due to subset type

### ISSUE THREAD

**Issue by seanmcl** [dafny-lang/dafny#2752]
```
type foo = x: object? | x != null witness *

function method m(): foo {
  null
}

method Main() ensures false {
  var y := m();
  assert y == null;
  assert y != null;
}
```

**Comment by cpitclaudel** [comment]
Thanks for catching that, and also ouch.

The following shows that the issue is a type inference bug:

```
type EmptyQ = x: object? | false witness *
type Empty = x: object | false witness *

method Main() {
  var xq := null as EmptyQ; // No error
  var x := null as Empty; // Error
}
```

Specifically, the resolver infers that the type of `null` in the first instance assignment is `Empty`, not `object?`.  In contrast, the second instance is correctly inferred.

The result is that the verifier skips the subtyping check.

**Comment by seanmcl** [comment]
Do you mean the first assignment is typed as EmptyQ?
