### ISSUE TITLE
Behaviour of Dafny program command-line arguments with "dafny build" inconsistent on Javascript

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#2867]
```dafny
// An attempt at a CLI that behaves the same in all target languages
method Main(args: seq<string>) {
  if |args| == 0 {
    return;
  }
  print args[1..], "\n";
}
```

```
> dafny /compile:3 src/Scratch.dfy /compileTarget:js --args 1 2 3

Dafny program verifier finished with 0 verified, 0 errors
Running...

1,2,3
> dafny build -t:js src/Scratch.dfy

Dafny program verifier finished with 1 verified, 0 errors
> a483e79acc1e:libraries salkeldr$ node src/Scratch.js 1 2 3
/Users/salkeldr/Documents/GitHub/libraries/src/Scratch.js,1,2,3
```

**Comment by robin-aws** [comment]
This may reduce to a documentation issue as I'm not sure whether it's actually solvable.

**Comment by cpitclaudel** [comment]
Should be solvable: we need to decide whether `args` includes the name of the binary or not (cc @MikaelMayer)

**Comment by davidcok** [comment]
I'd vote that `args` does not include the binary; but if it does then it should always be exactly the first element of `args` -- the content of `args[0]` might be platform-dependent and might be an empty string, but `args[1..] would be the same on all platforms for the same user command-line.

**Comment by MikaelMayer** [comment]
Ouch, that indeed an inconsistency that does not exists for C# as it's tested.

**Comment by MikaelMayer** [comment]
I'm left with one problem and a potential solution.

* `dotnet library.dll arg1 arg2` will put ` arg1, arg2` in the list of arguments. So I'm adding "dotnet" manually in the runtime, because in C++, the name of the executable is always included.
* `node library.js arg1 arg2` will put `node, library.js, arg1, arg2` in the list of arguments. Two more arguments than dotnet.

So now, I need to remove one element of the argument array in node to be consistent. I could either
* Remove "node".
* Remove "library.js"
* Combine "node" and "library js" into two. Since the first argument is platform-dependent anyway, I think this is best.

**Comment by davidcok** [comment]
I suggest that everything that is the executable got into the 0th argument, space separated, so args[0] == "dotnet library.dll" or "node library.js"
