### ISSUE TITLE
--enforce-determinism should require --strict-definite-assignment

### ISSUE THREAD

**Issue by cpitclaudel** [dafny-lang/dafny#2959]
In #2933 `-definiteAssignment` was split into two options:

```
  --strict-definite-assignment                 Additionally enforce definite-assignment rules for 
                                               variables that are ghost or whose types support auto-initialisation,
                                               so it is enforced for all non-yield-parameter variables and fields. [default: False]
  --enforce-determinism                        Check that only deterministic statements are used, so that
                                               values seen during execution will be the same in every run of
                                               the program. [default: False]
```

Previously, these two options couldn't be set separately: enforce-determinism couldn't be set without also setting strict-definite-assignment.  Now, they can be set separately, but the result is that `--enforce-determinism` does not actually enforce (language-level) determinism, as shown by the programs below:

```
method NondetIf() returns (x: int) {
  if * {
    x := 0;
  } else {
    x := 1;
  }
}

method AlsoNondetIf() returns (x: int) {
  var b: bool;
  if b {
    x := 0;
  } else {
    x := 1;
  }
}

method NondetAssign() returns (x: int) {
  x := *;
}

method AlsoNondetAssignButAccepted() returns (x: int) {
  var y: int;
  x := y;
}
```

(I say language-level determinism because in practice all our compilers do use deterministic initialization for auto-init types, which also means that this isn't a soundness bug, thankfully.)

To fix this, I propose that we change `--enforce-determinism` to automatically imply `--strict-definite-assignment` (this will match the logic original flag).  Additionally, we might consider renaming `--enforce-determinism`, since it doesn't forbid non-deterministic `:extern` methods.

**Comment by keyboardDrummer** [comment]
I don't understand your concern yet. In your above example, `NondetIf` and `NondetAssign` are flagged as errors by `--enforce-determinism`. The other two are not, but they also have deterministic runtime behavior so that seems fine to me. What's the problem?

**Comment by cpitclaudel** [comment]
> The other two are not, but they also have deterministic runtime behavior

All four programs currently have deterministic runtime behavior when compiled, but AFAIK that's an accident of our compilation strategy (not a guarantee of the language). I could be wrong.

**Comment by cpitclaudel** [comment]
> Do you see a use-case for using only --strict-definite-assignment ?

Yes: `enforce-determinism` is too strong for many use cases, as it disallows code like this:

```
function Unwrap(s: set<int>): (i: int)
  requires |s| == 1
  ensures s == {i}
{
  var i :| i in s;
  assert s == (s - {i}) + {i};
  i
} by method {
  i :| i in s;
}
```

**Comment by keyboardDrummer** [comment]
Is there a use to having the Dafny spec allow auto-init types to be non-deterministic? My intuition is that they would be deterministic, so having `--enforce-determinism` require me to init variables of those types is surprising.

Also, `strict-definite-assignment` does two things, both auto-init types now require definite assignment, but also ghost variables. The latter doesn't seem to be something that's needed for determinism, right?

> > Do you see a use-case for using only --strict-definite-assignment ?
> 
> Yes: `enforce-determinism` is too strong for many use cases, as it disallows code like this:
> 

That seems like a use-case for not using `enforce-determinism`, but it doesn't advocate for using `strict-definite-assignment`, does it?

I don't like the option `--strict-definite-assignment` since the name doesn't tell me when to use it. `strict` implies safer, so should I always use this? It seems like unless I want determinism, there's no reason that I should. How about we remove `strict-definite-assignment` and make `enforce-determinism` turn on `strict-definite-assignment` ?

**Comment by RustanLeino** [comment]
Dafny is a language that embraces nondeterminism. It can afford to do so because the verifier will check that all values and paths, no matter how nondeterministic, satisfy specifications. I think auto-initialization should not promise determinism.

I could imagine that `strict-definite-assignment` would apply to both ghost and non-ghost code, where `enforce-determinism` could apply to just non-ghost code. It seems that the `/definiteAssignment` switch today does not have such a mode (that is, a mode `4` that is to `1` what `3` is to `2`).
