### ISSUE TITLE
[Bug]: method verifies when value is passed in as an argument, but not when produced by a function call

### ISSUE THREAD

**Issue by erniecohen** [dafny-lang/dafny#3094]
### Dafny version

3.9.1

### Code to produce this issue

```dafny
class C {}
function method cs():set<C> 
method test0(s:set<C>) {
    var c := new C;
    assert c !in s; // succeeds
}
method test1() { test0(cs()); } // no problem
method test() {
    var s := cs();
    var c := new C;
    assert c !in s; // fails
}
```

### What happened?

The first two methods verify; the third does not (but presumably should).

### What type of Operating System are you seeing the problem on?

Mac

**Comment by MikaelMayer** [comment]
This is not a bug actually, it's an incompleteness of Dafny to ensure better verification performance.

The problem comes from the fact that Dafny does not create an `allocated()` axiom for every expression in the scope, because that could drown the verifier on often mostly useless facts. This axiom is instantiated though for in-parameters, so this is why it works in your first case. The second case wouldn't work if you try to `var c:= new C; assert c !in S;` for example.
Fortunately, there is a workaround for that using the knowledge the axiom is instantiated for in-parameters:

```dafny
class C {}
function method cs():set<C> 
lemma IsAllocated<T>(t: T)
  ensures allocated(t) { // Easily proved
}
method test() {
    var s := cs();
    IsAllocated(s); // now we know that allocated(s) holds. and at this point, !allocated(c) holds
    var c := new C;
    assert c !in s; // Dafny can now prove this.
}
```
