### ISSUE TITLE
Dafny fails to check type characteristics in specification clauses

### ISSUE THREAD

**Issue by atomb** [dafny-lang/dafny#3150]
### Dafny version

3.9.1 (and 35a047871ef6)

### Code to produce this issue

```dafny
predicate P<T(!new)>(x: T)

method M<T>(x: T)
  requires P(x)
```

### Command to run and resulting output

```code
# dafny /compile:0 /trace NotNew.dfy

Dafny program verifier finished with 0 verified, 0 errors
```

### What happened?

Dafny should have complained that, in the specification of `M`, `P` cannot be applied to `x` because `x` is not known to be `!new`.

If you add `assert P(x);` to the body of `M`, Dafny does complain.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by RustanLeino** [comment]
Yes, this looks like a bug.

**Comment by robin-aws** [comment]
I hit a similar case of type-unsafety in specifications myself:

```dafny
datatype Any<T> = Any(value: T)
function method As<T, R>(a: Any<T>): R
    ensures As(a) == a   // should be rejected as a type mismatch but is allowed
```

From @RustanLeino (not as relevant to this issue but still suggests this kind of laxness was intentional at some point):

There’s an allowance in the Dafny type system that you can sometimes compare against a type parameter. The purpose of this had been to be able to write:

```dafny
method FillMyArray<X>(a: array<int>, unrelatedArray: array<X>)
  requires a != unrelatedArray
  modifies a
```

Evidently, that’s also allowed for datatypes, which doesn’t have the same use case and would be better disallowed. In fact, even the case for arrays is probably better disallowed these days, because there’s a simple way to write it with as (which, relative to arrays and type parameters, is a newfangled construct in Dafny):

```dafny
  requires a != unrelatedArray as object
```

**Comment by RustanLeino** [comment]
The issue reported by @atomb above was fixed in https://github.com/dafny-lang/dafny/pull/4928.

@robin-aws 's issues seem unrelated to me. The behavior of the `Any` example is still exhibited by Dafny, by both the old and new resolver. The behavior of the `FillMyArray` example is as Robin described it for the old resolver and has been fixed as Robin mentioned in the new resolver.

I suggest we close this Issue and record Robin's `Any` example in a new, separate Issue.

**Comment by atomb** [comment]
Migrated half of this to #5144, and confirmed that the original example is now rejected.
