### ISSUE TITLE
importing qualified module in a refining module doesn't recognize module imported in parent

### ISSUE THREAD

**Issue by tjhance** [dafny-lang/dafny#327]
This code:
```
module A {
}

module B {
  import A
}

module C {
  import B
}

module D refines C {
  import A = B.A
}
```
gives the error message:
```
$ dafny test1.dfy 
Dafny 2.3.0.10506
test1.dfy(13,13): Error: module B does not exist (position 0 in path B.A)
1 resolution/type errors detected in test1.dfy
```

One might infer from this error message that the right fix is to re-import B from D. That
doesn't work either:
```
module A {
}

module B {
  import A
}

module C {
  import B
}

module D refines C {
  import B
  import A = B.A
}
```
gives this error message:
```
$ dafny test2.dfy 
Dafny 2.3.0.10506
test2.dfy(13,9): Error: a module (B) can only refine a module facade
```

My guess is that the second example is expected, and the first is not.

**Comment by davidcok** [comment]
The problem is that the import B.A is resolved before the containing module D is resolved, because the import looks like a submodule, and submodules are ordered before containing modules. The solution is, when looking up B, and not finding it in D, to look again in the
refinement parent, if there is one. We do not need to look further because the refinement parent will already be fully resolved.

PR973
