### ISSUE TITLE
type inference weakness: fails to unify inferred template params across case statement

### ISSUE THREAD

**Issue by tjhance** [dafny-lang/dafny#330]
In this code, one would expect that the use of `None` would be inferred to have type `Option<int>` and therefore `T(none)` would have type `T<int>`, thus matching the return type and also the type from the other case.
```
datatype Option<A> = Some(value: A) | None

datatype T<A> = T(value: Option<A>)

function f(t: T<int>) : T<int>
{
  match t.value {
    case Some(val) => T(Some(val))
    case None => T(None)
  }
}
```
Unfortunately we get this error message:
```
$ dafny a.dfy 
Dafny 2.3.0.10506
a.dfy(9,18): Error: type of case bodies do not agree (found T<?>, previous types T<int>) (invariant type parameter would require int = ?)
1 resolution/type errors detected in a.dfy
```

Well, this wouldn't be so bad if we could specify the type parameter
either with `T(None<int>)` or `T<int>(None)`, but neither of these work and just give an error that these constructors don't take type params. This was the easiest workaround I could find:

```
datatype Option<A> = Some(value: A) | None

datatype T<A> = T(value: Option<A>)

function f(t: T<int>) : T<int>
{
  match t.value {
    case Some(val) => T(Some(val))
    case None => (
      var none : Option<int> := None;
      T(none)
    )
  }
}
```

**Comment by davidcok** [comment]
PR #692. Problem already fixed. Added tests.

**Comment by RustanLeino** [comment]
A remark about other workarounds:

The attempted expressions `T(None<int>)` and `T<int>(None)` are, as noted, not legal. This is because the type parameter does not go with the name of the constructor, but with the type. To use that form, you thus also need to qualify the constructor name with the name of the type (so that you have some place to hang the explicit type instantiation). So, here are three other workarounds:

    T<int>.T(None)
    T(Option<int>.None)
    T<int>.T(Option<int>.None)

**Comment by davidcok** [comment]
Oops. Thanks for catching my cut&paste mistake. I'll put it back on my task list.
