### ISSUE TITLE
Make distinction between partial and total correctness more evident

### ISSUE THREAD

**Issue by jtristan** [dafny-lang/dafny#3417]
### Summary

By default, Dafny guarantees total correctness. However, partial correctness is possible, but it is implicit and could mislead a user into misunderstanding what has been proven. 

### Background and Motivation

By default, Dafny guarantees total correctness. As a consequence, a method like the following is not valid:
```
method bad()
{
	bad();
}
```
This method definition is rejected because termination cannot be proved.

However, the decrease clause allows to bypass such check, as in the following example: 
```
method bad()
	decreases *
	ensures false
{
	bad();
}
```

In this case, the postcondition should be understood as: if the method returns, then the postcondition holds, a partial correctness property. 

Any caller of method bad must then also be declared with the clause decreases *
```
method foo()
	decreases *
{
	bad();
}
```

Note that there are genuine cases where one might want to use the decrease * clause while defining meaningful code with relevant partial correctness property. This can happen, for example, if you a write Dafny method that converts a graph representation of a program represented in C# into another representation in Dafny. 

Moreover, if Dafny were to be extended with concurrency, we are likely to make heavier use of partial correctness.

### Proposed Feature

We could introduce a new keyword, for example partial, to indicate when the specification of a method is meant to be understood as partial correctness. 

With the examples above, that could give:
```
partial method bad()
	ensures false
{
	bad();
}

partial method foo()
{
	bad();
}
```

And the error message when the keyword is forgotten could be reworded to explain to the user that
the guarantees hold only if the method actually terminates, and that if they want total correctness,
they must provide a decrease clause. 

Since partial is also a useful concept for functions with a require, we might of course consider other keywords
that might make it even more useful to the user that they need to be mindful of the guarantees, for example 
by using the keyword **weak**.

**Comment by MikaelMayer** [comment]
Thanks for submitting this feature request ! Could you elaborate more on the problem? Like, have you encountered a case where it was hard to see `decreases *` or a testimonial indicating it was not understandable?

Every time I see `decreases *` I know now that what it means: I'm not providing an expression to decrease till a bottom line, so the method might not terminate. So I like this keyword phrase. Perhaps we could enforce that it is stated at the beginning of the specification so that it is more obvious and not hidden amid other specifications?

On the keywords you mention
* `partial` is used in C# in the context of partially _defined_ classes, so users might expect a partial method to be defined also somewhere else.
* `weak` is sometimes used in the context of garbage collection (WeakReference) to indicate that it should not be expected that the object is still pointed at.

**Comment by stefan-aws** [comment]
I generally like the proposal. But I find that using the keyword as in `partial method` gives the wrong impression that one is dealing with a partially defined method, where as one is actually dealing, in some sense, with a partially defined post-condition (that is guaranteed to be true only in case of termination). Therefore, what do you think about:

```
method bad()
	partial(ly) ensures false
{
	bad();
}

**Comment by stefan-aws** [comment]
Of course, one could also make partial correctness the default, and introduce a `total(ly)` keyword. However, I'd discourage us from doing so. First, since we currently work with total correctness as default, it would change the semantics, potentially resulting in broken code, or the incorrect impression that methods are (automatically) proven to terminate, even though they don't. Second, I believe that in general it is better to suggest to the user to prove (a bit) more than less. Otherwise, I think it is likely that many users will simply _never_ try to prove termination.

**Comment by atomb** [comment]
I also like the idea of making a clearer distinction between methods proven to terminate and those that aren't, though my initial reaction is that `partial` is too much of an inside term. Anyone who does research in verification will understand it, but it may seem opaque to developers who don't have that background. I wonder whether something that more directly mentions termination would be better, though the immediate, straightforward possibilities, like "potentially nonterminating", are too long and awkward.

**Comment by stefan-aws** [comment]
In respoind to @atomb, here another idea:

```
method bad()
	ensures false if terminating
{
	bad();
}

**Comment by MikaelMayer** [comment]
> In response to @atomb, here another idea:
> 
> ```
> method bad()
> 	ensures false if terminating
> {
> 	bad();
> }
> ```

That's an interesting one. What if there is no ensures clause?

**Comment by MikaelMayer** [comment]
What I miss from the description and from the issue description is **What is the problem with  `decreases *`.** ? And I don't see one frankly. It's not an attribute, it has clear meaning (skip the decreases checks), it is required on callers.

One problem I see is that the decreases might be under a lot of pre- and postconditions, so this is why one might not see it.
But with the auditor, this isn't a serious problem that justifies the introduction of a keyword.

`decreases *` does its job. I still need to find a compelling reason to change that. For example `{:opaque}` as a keyword makes sense, because of the twin `reveal` keyword.

**Comment by jtristan** [comment]
I can claim that {:opaque} does its job and has a clear meaning, or that "function method" did its job and had a clear meaning, so perhaps we can avoid this kind of arguments. 

You say that it has a clear meaning and then summarize it as "skip the decreases checks". That's precisely my concern about it. I have now had multiple discussions with Dafny users who have a moment of panic when they realize that you can write a program like "bad" above. They think we messed up because, surely, every term in Dafny must terminate. It makes sense they would have such an expectation since by default, Dafny focuses on total correctness. And indeed they didn't realize that decreases * doesn't just mean "skip the decreases checks" but also mean that you have given up on total correctness and that postconditions have to be interpreted differently. 

Nevertheless, I don't think this is worth wasting time over, so I will retract the proposal and close the discussion.
