### ISSUE TITLE
Interfacing with c# libraries results in errors in transpiled code

### ISSUE THREAD

**Issue by MatthewBennington** [dafny-lang/dafny#346]
I have two files:

test.dfy:
```
module {:extern "HelloWorld"} HelloWorld {
    class {:extern "HelloWorld"} HelloWorld {
        static method {:extern "sayHello"} sayHello() returns (s: string)
    }
}

method Main() {
    var x := HelloWorld.HelloWorld.sayHello();
    print x;
}
```

test-externs.cs
```
namespace HelloWorld {
    public partial class HelloWorld {
        public static Dafny.Sequence<char> sayHello() {
            return Dafny.Sequence<char>.FromString("Hello, World!");
        }
    }
}
```

I'm trying to compile with `dafny /compile:3 test-externs.cs test.dfy`, but this results in the following error:
```
Dafny 2.3.0.10506

Dafny program verifier finished with 1 verified, 0 errors
Compiled program written to test.cs
Errors compiling program
test.cs(1514,29) : error CS1501: No overload for method `sayHello' takes `1' arguments
```

I'm still learning Dafny, so I'm sure that this is some error in my code, but I can't figure it out based on the error message I'm getting. Anyway, here's chunk of the transpiled c# code:

```
namespace _module {


  public partial class __default {
    public static void Main()
    {
    TAIL_CALL_START: ;
      Dafny.Sequence<char> _12_x;
      Dafny.Sequence<char> _out0;
      HelloWorld.HelloWorld.sayHello(out _out0);
      _12_x = _out0;
      Dafny.Helpers.Print(_12_x);
    }
  }
} // end of namespace _module
```

**Comment by samuelgruetter** [comment]
Your example works fine for me, using Dafny master (commit 1cee786c549ae95888e87def890bb8294b6081e4 from Tue Aug 6 is the one I tried).

```
$ dafny /compile:3 test-externs.cs test.dfy
Dafny 2.3.0.10506

Dafny program verifier finished with 1 verified, 0 errors
Compiled program written to test.cs
Running...

Hello, World!
```

Dafny used to compile all method return values to C# out-parameters. Recently, this was changed: Now if the method returns multiple values, it's compiled to out-parameters, and if the method returns a single return value, it's compiled to a "normal" return.

If you absolutely want to continue using your older Dafny version, you could fix the problem by using an out-parameter in C#:
```
    public static void sayHello(out Dafny.Sequence<char> res) {
      res = Dafny.Sequence<char>.FromString("Hello, World!");
    }
```

But I'd strongly suggest updating to the most recent Dafny, because otherwise you can't interface with C# libraries you don't control which return values instead of `void` and out-parameters.

**Comment by MatthewBennington** [comment]
I was using commit 6f48c4a from the latest release. Building from the latest commit fixed the issue, thanks!
