### ISSUE TITLE
Allow annotating methods/functions to control inlining for test generation

### ISSUE THREAD

**Issue by codyroux** [dafny-lang/dafny#3716]
### Summary

Have an annotation or option to mark a given method as "to be covered" if it is reachable in the call graph of the entry point for test generation.

### Background and Motivation

Currently one way to control the coverage requirements of the test generation is to use the `--inline-depth n` argument, which asks for coverage of all the blocks of code within methods at most `n` steps away from the entry point in the call-graph. However there is a strong potential here for path explosion, the usual problem encountered with this kind of symbolic test generation.

Ideally things would be a bit more fine-grained, by marking exactly which methods should be covered, if reachable from the entry point.

### Proposed Feature

One could imagine either a command line feature like `--inline-for-tests SomeModule.SomeMethod`, or an attribute `{:test-inline}` attached to the method/function method declaration itself.

I can imagine 2 semantics for this annotation:

- The method, *and all methods above it in the call graph* are inlined, and the test generation tool attempts to cover each block of the annotated method using the usual approach.
- The method is inlined iff all the methods above it are also marked as inlined (or if it is directly reachable in 1 step from the entry point).

The second semantics seems more "honest" in terms of the semantics, but may lead to confusing behavior if the method is "hidden" by a non-inlined method. Maybe a warning is appropriate in this case.

### Alternatives

I don't currently have a case where this feature allows test generation to succeed (i.e. both terminate and cover the desired blocks) when it otherwise would fail, though I suspect I will soon run into this. I'm not sure what an alternative would be.

**Comment by keyboardDrummer** [comment]
> I am currently leaning towards implementing this as a command line feature rather than an attribute since this would allow generating different kinds of tests for different methods in the same file without necessarily having to edit that file in-between attempts.

For an automated setup, referring to methods through a command line option seems more fragile than being able to annotate these methods in-line, since renaming part of the method's qualified name would break the CLI call. I think being able to annotate in-line should be possible.

Can you show using an example what different kinds of tests you'd like to generate for the same method? I'm afraid I don't know the existing test generation feature well. I'm guessing that inline-depth=n attempts to create a set of tests for a particular root method, that also tries to cover code reachable from the root in n calls.

Wouldn't it make more sense to test each method in isolation, by using inline-depth=0, but specifing all methods as roots, so each method has a set of tests intended to only test that method?

**Comment by Dargones** [comment]
Thank you, @keyboardDrummer for weighting in on this. The danger of breaking the CLI call makes sense to me - let me redo the related PR to use the annotations.

You are right about the current behavior of the `inline-depth` option.  The reason to use inlining is model-based testing. Suppose you have an implementation of some functionality that is not written in Dafny and an equivalent Dafny model. You can then generate tests from the model and then run the tests on the other implementation. Inlining allows generating tests for some high-level API call in which case the low-level details of the model and the implementation don't have to exactly match.

**Comment by codyroux** [comment]
> Wouldn't it make more sense to test each method in isolation, by using inline-depth=0, but specifing all methods as roots, so each method has a set of tests intended to only test that method?

It's a bit more subtle than that @keyboardDrummer: imagine you have a method of the following form:

```
method MyMethodToTest(someInput: SomeType) {
     var foo := SomeBoringSetup(someInput);
     var toTest := TheInterestingWork(foo);
     expect toTest;
     SomeBoringCleanup();
}
```

We want to test the _paths_ in `TheInterestingWork` method, but unfolding at level 1 will create an explosion. You might suggest that we just test `TheInterestingWork`, but

1.  The `SomeBoringSetup` might actually be doing non-trivial input massaging (which we'd have to specify in the postcondition, of course).
2. `TheInterestingWork` _itself_ might have some "boring" parts which we don't want to hassle the test generator with!

This is why you want fine-grained control over inlining when doing test generation.

**Comment by keyboardDrummer** [comment]
> Thank you, @keyboardDrummer for weighting in on this. The danger of breaking the CLI call makes sense to me - let me redo the related PR to use the annotations.
> 
> You are right about the current behavior of the `inline-depth` option. The reason to use inlining is model-based testing. Suppose you have an implementation of some functionality that is not written in Dafny and an equivalent Dafny model. You can then generate tests from the model and then run the tests on the other implementation. Inlining allows generating tests for some high-level API call in which case the low-level details of the model and the implementation don't have to exactly match.

Makes sense!

What's the reason you don't want to fully inline the call-graph of the root method? @codyroux mentions path explosion. That doesn't happen when generating tests using block coverage, right? Would it makes sense for the path based coverage to only take paths up to a maximum length X in the call-graph, where the paths don't necessarily need to start at the root?

> I am currently leaning towards implementing this as a command line feature rather than an attribute since this would allow generating different kinds of tests for different methods in the same file without necessarily having to edit that file in-between attempts.

I would suggest placing the attributes on the root method, so you can customise the inlining per root method.

> Have an annotation or option to mark a given method as "to be covered" if it is reachable in the call graph of the entry point for test generation.

Have we considered reversing the specification of what to inline, so one has to specify which methods _not_ to inline? It seems safer to bias for covering too much, forcing the user to constrain the inlining it to reduce test case explosion, instead of biasing towards covering too little, which doesn't give a clear indication of a problem to the user.

**Comment by Dargones** [comment]
Thank you, @codyroux and @keyboardDrummer! I have made a new PR (#3865) that I think gets much closer to the solution outlined here. Below are some notes wrt the PR:

> What's the reason you don't want to fully inline the call-graph of the root method? @codyroux mentions path explosion. That doesn't happen when generating tests using block coverage, right? Would it makes sense for the path based coverage to only take paths up to a maximum length X in the call-graph, where the paths don't necessarily need to start at the root?

Even if you use block coverage, path explosion can happen because one method might have to be inlined several times, once for each call site (or even more times if there are different paths to the said call-sites or if there is recursion). So I think part of the reason for allowing more fine-grained control over inlining is because reasoning about which methods can cause such path explosions automatically is difficult.

> I would suggest placing the attributes on the root method, even though they may refer to other methods, so you can customise the inlining per root method.

This would definitely offer more flexibility but would potentially also lead to prohibitively long method annotations, so I am wondering if it is OK to have a single inlining behavior for all tests. My guess is that in most cases the inlining behavior wouldn't need to change even if the entry points for the tests are different.

> Have we considered reversing the specification of what to inline, so one has to specify which methods not to inline? It seems safer to bias for covering too much, forcing the user to constrain the inlining to reduce test case explosion, instead of biasing towards covering too little, which doesn't give a clear indication of a problem to the user.

An argument for having an attribute on the methods that are to be inlined is that this gives the user the control on how much to unroll recursive methods for (see the example in the PR). In general, inlining is very costly (in particular inlining might require parsing all included modules at once), so I think the optimal solution would be to have an option that turns it off and maybe to have it turned off by default.
