### ISSUE TITLE
First argument passed to Main is string "dotnet"

### ISSUE THREAD

**Issue by jtristan** [dafny-lang/dafny#3717]
### Dafny version

4.0.0

### Code to produce this issue

```dafny
method Main(args: seq<string>) {

    for i := 0 to |args| {
        print(args[i] + "\n");
    }

}
```

### Command to run and resulting output

```code
% dafny run Notes/Main.dfy 3

Dafny program verifier finished with 1 verified, 0 errors
dotnet
3
```

### What happened?

I did not expect for the first argument to be the string "dotnet".

### What type of operating system are you experiencing the problem on?

Mac

**Comment by MikaelMayer** [comment]
This is not a bug, this is by design. The first argument of most programs run on the command-line is actually the script itself. For example, for "python" it's the python script. For C++ programs, it's the name of the executable.
For Dafny, we decided it would be the platform + some information about it if available.
