### ISSUE TITLE
Document: Missing property of map update?

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#3737]
### Dafny version

4.0.0

### Code to produce this issue

```dafny
method mmm<K(==),V(==)>(m: map<K,V>, k: K, v: V) {
    var mm := m[k := v];
    //assert k in mm.Keys;
    assert v in mm.Values;
  }
```

### What happened?

The assert that v is now in mm.Values fails to verify. This seems an elementary property that ought to be implicitly true. And then, confusingly, it verifies just fine if the commented out line is uncommented.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by RustanLeino** [comment]
It's true, you do need that `assert k in mm.Keys`. The reason is that `m.Values` is defined as the following set:

``` dafny
set k: K, v: V | k in m.Keys && m[k] == v :: v
```

Equivalently, you can think of this set as

``` dafny
set v: V | exists k: K :: k in m.Keys && m[k] == v
```

This kind of set comprehension (or the simpler set comprehension with the `exists`) is harder to use. In particular, it requires a term like `_ in m.Keys` to be triggered.

This would be difficult to change in the verifier. I suggest we instead document this fact about `Values` in either the reference manual or in an FAQ.

**Comment by davidcok** [comment]
I'll include it in a FAQ somewhere
