### ISSUE TITLE
Function Methods error

### ISSUE THREAD

**Issue by rosemarymonahan** [dafny-lang/dafny#3794]
Has support for Function methods been removed? Dafny 4.0.0.50303 Windows 10 and windows 11 and getting errors on code that worked previously e.g. in the code below:

class ChecksumMachine {
  ghost var data: string 
  var cs: int 

  predicate Valid()
    reads this 
{
    cs == Hash(data) 
 
  }
  constructor ()
    ensures Valid() && data == ""
  {
    data, cs := "", 0;
  }

  function method Checksum(): int
    requires Valid()
    reads this
    ensures Checksum() == Hash(data)
    ensures Valid() 
    {   
            cs 
    }
}

method Main() {
  var m := new ChecksumMachine();
  m.Append("green");
  m.Append("grass");
  var c := m.Checksum();
  print "Checksum is ", c, "\n";
}

function method Hash(s: string): int {
  SumChars(s) % 137
}

function method SumChars(s: string): int 
decreases  s
 {
  if |s| == 0 then 0 else
    var last := |s| - 1;
    SumChars(s[..last]) + s[last] as int   // as converts char to int
}

**Comment by davidcok** [comment]
Yes. See the migration guide for 4.0: https://github.com/dafny-lang/ide-vscode/wiki/Quick-migration-guide-from-Dafny-3.X-to-Dafny-4.0

The syntax has been made more consistent: 4.0 -- method and function / ghost method and ghost function
instead of 3.x -- method and function method / ghost method and function.

You can control the syntax with this option --function-syntax:4 or --function-syntax:3 but 4 is now the default.
