### ISSUE TITLE
Multiple Occurences of `--boogie` 

### ISSUE THREAD

**Issue by DavePearce** [dafny-lang/dafny#3836]
### Dafny version

4.0

### Code to produce this issue

```dafny
function id(x:int) : (r:int) { x }
```

### Command to run and resulting output

```code
dafny verify --boogie "/randomSeedIterations:0" --boogie "/vcsLoad:2" tmp.dfy
```

### What happened?
When multiple occurrences of the cli switch `--boogie` are given on the command-line, all but the last are ignored.  We can see this because the above `dafny` command returns successfully.  However, it should report an error on the malformed input given in `--boogie "/randomSeedIterations:0"`.  Specifically, this command line does fail as expected:

```
dafny verify --boogie "/randomSeedIterations:0" tmp.dfy

dafny: Error: Invalid argument "0" to option /randomSeedIterations
Use /help for available options
```

This behaviour is pretty confusing, and had me stumped for quite a while. 

### What type of operating system are you experiencing the problem on?

Linux

**Comment by keyboardDrummer** [comment]
There was a recent change to the Dafny CLI that lets any options that have an arity of at most one, to be specified multiple times, where only the last specified value is used. This is apparently a common behavior of CLIs that allows overwriting values specified in one location with new values specified elsewhere. Relevant issue: #3571 @davidcok 

The Boogie option has an arity of 0-1, so it was affected by this change. Maybe for the Boogie option, this behavior is extra confusing because one might expect the Boogie option to have an arity of *. If you want, I can change the Boogie arity to *, so both `--boogie "/randomSeedIterations:0" --boogie "/vcsLoad:2"` and `--boogie "/randomSeedIterations:0 /vcsLoad:2"` would be valid inputs.

**Comment by DavePearce** [comment]
Personally, I think that makes sense!!  

The other approach would be to provide a way of seeing the command line given to boogie so we can check whether the command-line is what we're is expecting!

**Comment by keyboardDrummer** [comment]
> The other approach would be to provide a way of seeing the command line given to boogie so we can check whether the command-line is what we're is expecting!

Yes that'd be a great feature but Boogie's options object is current unable of printing itself, and we'd have to define all the options using a higher level abstraction to implement that well ^,^
