### ISSUE TITLE
Incorrect cardinality of set and multiset<array> - Java Miscompilation error

### ISSUE THREAD

**Issue by Dilan-s** [dafny-lang/dafny#3871]
### Dafny version

4.0.0

### Code to produce this issue

```dafny
method Main() returns () {
    var v_array: array<int> := new int[] [1, 2];

    var v_int_s: int := |{v_array}|;
    assert(v_int_s == 1);
    print v_int_s, "\n";

    var v_int_m: int := |multiset{v_array}|;
    assert(v_int_m == 1);
    print v_int_m, "\n";
}
```

### Command to run and resulting output

```code
$ dafny /compile:4 /compileTarget:js test.dfy
1
1

$ dafny /compile:4 /compileTarget:cs test.dfy
1
1

$ dafny /compile:4 /compileTarget:py test.dfy
1
1

$ dafny /compile:4 /compileTarget:go test.dfy
1
1

$ dafny /compile:4 /compileTarget:java test.dfy
2
2
```

### What happened?

Dafny verifies program but produces different outputs depending on the compilation target language when calculating the size of a set/multiset containing arrays (appearing that the array is flattened in Java but not in the other languages).

### What type of operating system are you experiencing the problem on?

Linux

**Comment by Dilan-s** [comment]
This also leads to further issues with operations:

The following program can be compiled into a jar with no errors:
```
method Main() returns ()
{

  var a_1: array<int> := new int[1] [0];
  var a_2: array<int> := new int[1] [0];
  var a_3: array<int> := new int[1] [0];

  print ({a_1} !! {a_2, a_3}), "\n";
}
```

However the following program, cannot and throws the error detailed below:
```
method Main() returns ()
{

  var a_1: array<int> := new int[1] [0];
  var a_2: array<int> := new int[1] [0];
  var a_3: array<int> := new int[1] [0];

  print ({a_2, a_3} !! {a_1}), "\n";
}
```
Compiling output:
```
error: incompatible types: inference variable T has incompatible bounds
    System.out.print(java.lang.String.valueOf((dafny.DafnySet.of(_1_a__2, _2_a__3)).<java.math.BigInteger[]>disjoint(dafny.DafnySet.of(_0_a__1))));
                                                                                   ^
    lower bounds: BigInteger[],Object
    lower bounds: BigInteger
  where T is a type-variable:
    T extends Object declared in method <T>of(T...)

```

**Comment by robin-aws** [comment]
The root cause here is the same in both cases: the Java runtime uses varargs methods like this for instantiating collections:

```java
public static <T> DafnyMultiset<T> of(T ... args) {
    return new DafnyMultiset<T>(Arrays.asList(args));
}
```

When such methods are passed a single array-typed value, Java resolves the ambiguity by splatting the array values into individual arguments instead of keeping it as a single argument.

The fix is likely to just not use varargs in the generated code, since there is only marginal benefit to readability and this edge case will always exist otherwise.

**Comment by ssomayyajula** [comment]
Variadic `of()` is called only by `EmitCollectionDisplay()` in the Java backend, which itself is called in three places: when handling display expressions for sequences, multisets, and sets.

Curiously, sequences *don't* have this bug because the generic parameter `T` of `of()` is instantiated as `T'[]` for some `T'` using an explicit cast for the type descriptor associated to `T` in compiled code, so the varargs parameter becomes an *array of arrays*, which is what we want.

Because the Java backend (both the compiler and runtime) relies on varargs for collection display expressions, it might be less invasive to instead insert this kind of lateral cast for multisets and sets.
