### ISSUE TITLE
Include paths 

### ISSUE THREAD

**Issue by hmijail** [dafny-lang/dafny#4029]
### Summary

A CLI option to declare paths where included files will be searched for. 

### Background and Motivation

Included files are specified by their path, be it relative or absolute. This works well for monolithic projects, but doesn't allow a Dafny project to be modularized into smaller _independent_ projects.

To solve this kind of problem, C compilers use include paths where included files will be searched for.

### Proposed Feature

A CLI option to declare paths where included files will be searched for. 

Probably this should also support specifying files contained in a .doo library file; but note that an use case is to develop 2 projects simultaneously (say, a library and a client for that library). Typically such a library would be included as a git submodule in the git repo of the client.

### Alternatives

The lack of an include path complicates organization of projects, causing every client to duplicate the library, or needing every developer to agree on a directory structure.

**Comment by keyboardDrummer** [comment]
I'm marking this as a won't fix because we're working towards making include directives obsolete. Each independent project you describe will define a project file, a `dfyconfig.toml`, that specifies all the source files of that project, and can reference other `dfyconfig.toml` files that its files depend on. You will be able to import modules from any of the referenced files without using any includes.

Currently the Dafny IDE still needs include directives to work but we're working on resolving that.

**Comment by hmijail** [comment]
Looking forward to that. Thank you!
