### ISSUE TITLE
Dafny passes method attributes to Boogie raw, causing unsoundness

### ISSUE THREAD

**Issue by Dargones** [dafny-lang/dafny#4204]
### Dafny version

4.1.0

### Code to produce this issue

```dafny
function {:inline 1} b(i:int):int {1/i}
function a():int { b(0)/1 }
```

### Command to run and resulting output

```code
> dafny FILE.dfy
Dafny program verifier finished with 1 verified, 0 errors
Compiled assembly into FILE.dll
```

### What happened?

As far as I understand, Dafny is not intended to support the `:inline` attribute and I doubt anyone uses it (search for `"function {:inline 1}" AND language:dafny` does not return anything on GitHub), so the bug probably has no impact on Dafny users. That said, it appears that Dafny performs no checks on which attributes it passes on to Boogie, so I am wondering if there are other attributes that can similarly introduce unsoundness when interpreted by Boogie.

The solution that makes most sense to me would be to maintain in `DafnyOptions` a list of allowed attributes that would be passed on to Boogie (if there are such attributes), with an option for a Dafny extension to modify this list if necessary.

The reason Dafny verifies the code in this particular case is, I think, that Boogie ignores the `CheckWellformed$$_module.__default.b` procedure emitted by Dafny for function `b` because it has the `{:inline 1}` attribute on it. The corresponding procedure for `a` simply assumes that it can call `b(0)` because `b` has no preconditions.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by MikaelMayer** [comment]
Another attribute that is passed raw, causing unsoundness:

```dafny
method {:selective_checking} Test() {
  assert false;
}
```

**Comment by MikaelMayer** [comment]
Because some users have their own compilers for Dafny that make use of annotations, it would be cumbersome to ask them to write extensions for Dafny to not complain about their custom attributes.

What I think we could do better is the following:
1) Whitelist a set of options for methods that can be passed to Boogie
2) Any other option is removed for verification by Boogie
3) If an option is given like "{:boogie-X}", then it is kept and rewritten into "{:X}" for Boogie verification.

That way, we will never accidentally add an attribute that is not recognized, while not blocking users that make use of custom boogie attributes.

I think that we should do the following:
1) Have a list of attributes

**Comment by Dargones** [comment]
> That way, we will never accidentally add an attribute that is not recognized, while not blocking users that make use of custom boogie attributes.

I don't know enough about other extensions of Dafny but this would definitely work for test generation purposes!

**Comment by keyboardDrummer** [comment]
I think automatically moving any annotations from Dafny AST nodes to Boogie AST nodes is likely to lead to badly defined behavior, so I would remove that behavior entirely.

The Dafny compiler and custom extensions of it are then free to process annotations on Dafny AST nodes as they wish, and they may also map these to annotations on Boogie nodes.

**Comment by atomb** [comment]
While fixing this, we could do two additional things:
* Deprecate `:rlimit` in Dafny programs and recommend using `:resource_limit`, instead.
* Deprecate `:vcs_split_on_every_assert` in Dafny programs and recommend a new `:isolate_assertions`.
