### ISSUE TITLE
verification succeded with vscode but failed with latest compiled binary

### ISSUE THREAD

**Issue by ChuyueSun** [dafny-lang/dafny#4481]
### Dafny version

4.0.0.50303

### Code to produce this issue

```dafny
method only_once<a(==)>(a: array<a>, key: a) returns (b:bool)
ensures (multiset(a[..])[key] ==1 ) ==> b
{
  var i := 0;
  b := false;
  var keyCount := 0;
  while i < a.Length
  invariant 0 <= i <= a.Length
  invariant multiset(a[..i])[key] == keyCount
  invariant b <==> (keyCount == 1)
  {
    if (a[i] == key)
    { 
      keyCount := keyCount + 1; 
    }
    if (keyCount == 1)
    { b := true; }
    else
    { b := false; }
    i := i + 1;
    // assert multiset(a[..i])[key] == keyCount;
  }
  
  assert a[..a.Length] == a[..];
}
```

### Command to run and resulting output

```code
dafny verify only_once.dfy 

only_once.dfy(9,34): Error: this invariant could not be proved to be maintained by the loop
only_once.dfy(9,34): Related message: loop invariant violation
```

### What happened?

vscode dafny 3.1.2 verification is successful.

### What type of operating system are you experiencing the problem on?

Linux

**Comment by atomb** [comment]
I've tried verifying this file on the command line on macOS with Dafny 4.0.0, 4.1.0, and 4.2.0, and it successfully verified. I've also tried it on Linux with Dafny 3.12.0 and 4.0.0, with the same results. It also looks correct to me.

Ultimately, I think this is a case of verification brittleness. Because the general verification problem is undecidable, the results from Dafny should be interpreted as "proved" or "not able to be proved (but possibly correct)". Sometimes, small changes in a program, or in the underlying prover (including different builds of the Z3 SMT solver) can lead to the verification process giving up when it would otherwise succeed. I'm disappointed that it happens with a program this straightforward, however.

To help dig into this further, would you be able to try setting VS Code to use Dafny 4.2.0 and let me know what you see? Perhaps similarly if you set it to the latest nightly?

If you're not already doing this, you can run the exact same version of Dafny that VS Code is using by running
```
$HOME/.vscode/extensions/dafny-lang.ide-vscode-3.1.2/out/resources/4.2.0/github/dafny/dafny verify only_once.dfy
```
with the `4.2.0` replaced by whichever version you're using at the time.

**Comment by keyboardDrummer** [comment]
This verifies on Dafny 4.6 both on the CLI and in the IDE. Closing because there seems no current problem and the issue is stale.
