### ISSUE TITLE
Disjoint operator on imap produces ugly Boogie error

### ISSUE THREAD

**Issue by jonhnet** [dafny-lang/dafny#467]
Dafny's disjointness operator (!!) is defined over maps. When used over imaps, it produces an ugly Boogie error.
Example:
```
lemma foo()
{
  var x := imap[1:=2];
  var y := imap[2:=3];
  assert x !! y;
}
```
Output:

> /tmp/test__module.bpl(2689,24): Error: invalid type for argument 0 in application of Map#Disjoint: IMap Box Box (expected: Map U V)
> /tmp/test__module.bpl(2689,29): Error: invalid type for argument 1 in application of Map#Disjoint: IMap Box Box (expected: Map U V)

Example from Dafny 2.3.0.10506.

**Comment by jonhnet** [comment]
BTW, a pretty straightforward workaround is to just use !! over the .Keys of the imaps.

**Comment by RustanLeino** [comment]
Thanks for the bug report. Now that we have `.Keys`, I dislike using `u in x` and `x !! y` when `x` and `y` are maps. Thus, the fix I'm leaning toward here is to disallow `!!` on maps. That is, the workaround becomes the way of life. PR https://github.com/dafny-lang/dafny/pull/473.

What do you think?

**Comment by jonhnet** [comment]
I could live with that. It has the nice side effect of avoiding ambiguity about the definition of !! (Is it over keys or k,v pairs?)

Why not simply define map !! to produce an ast for map.keys !!?

**Comment by RustanLeino** [comment]
Yeah, that's the same reason I don't like `u in x` for a map `x` -- it looks like `u` would be a k,v pair.

Defining map `!!` to add in the `.Keys` (after type checking/inference, which establishes that we're indeed dealing with a map `!!`) would be one way to implement this map-domain disjointness. But since that still leaves the ambiguity, I'll go with nuking map `!!`.

**Comment by jonhnet** [comment]
Can't argue with that.
