### ISSUE TITLE
Enable finer-grained control of redundant- and contradictory-assumption warnings

### ISSUE THREAD

**Issue by alex-chew** [dafny-lang/dafny#4778]
### Background and Motivation

The `--warn-redundant-assumptions` and `--warn-contradictory-assumptions` options are useful for locating redundant and contradictory assumptions, but can generate false positives in nontrivial proofs. In some cases the proofs can be rewritten to avoid the warnings - but not always, it seems. It would be nice to be able to disable such warnings on a per-assertion (or per-declaration, or per-module) level.

Here is an excerpt from the Unicode libraries that generates contradictory-assumption warnings:
```dafny
  type CodeUnit
  type CodeUnitSeq = seq<CodeUnit>
  type MinimalWellFormedCodeUnitSeq = s: CodeUnitSeq
    | IsMinimalWellFormedCodeUnitSubsequence(s)
    witness *

  function IsMinimalWellFormedCodeUnitSubsequence(s: CodeUnitSeq): (b: bool)
    ensures b ==>
              && |s| > 0
              && forall i | 0 < i < |s| :: !IsMinimalWellFormedCodeUnitSubsequence(s[..i])
    decreases |s|

  /**
   * If minimal well-formed code unique subsequences `m1` and `m2` are prefixes of `s`, then they are equal.
   */
  lemma LemmaUniquePrefixMinimalWellFormedCodeUnitSeq(
    s: CodeUnitSeq, m1: MinimalWellFormedCodeUnitSeq, m2: MinimalWellFormedCodeUnitSeq
  )
    decreases |s|, |m1|, |m2|
    requires m1 <= s
    requires m2 <= s
    ensures m1 == m2
  {
    // Handle only the |m1| <= |m2| case explicitly
    if |m1| > |m2| {
      LemmaUniquePrefixMinimalWellFormedCodeUnitSeq(s, m2, m1);
    } else {
      assert m1 <= m2;
      assert m1 == m2 by {
        if m1 < m2 {
          // Here
          assert false by { assert m1 == m2[..|m1|]; }
        }
      }
    }
  }
```

The `assert false` near the end (labeled `// Here`) cannot be verified without the `by { ... }` portion. But the assertion within the `by { ... }` generates two warnings:

```
UnicodeEncodingForm.dfy(106,35): Error: proved using contradictory assumptions: assertion always holds
    |
106 |           assert false by { assert m1 == m2[..|m1|]; }
    |                                    ^^^^^^^^^^^^^^^^

UnicodeEncodingForm.dfy(106,41): Error: proved using contradictory assumptions: upper bound within range of sequence
    |
106 |           assert false by { assert m1 == m2[..|m1|]; }
    |                                          ^^^^^^^^^^
```

### Proposed Feature

This feature could, for example, be implemented as attributes (`{:warn_redundant_assumptions false}`, etc.) that are valid in assertions and at the declaration-/module-level.

**Comment by keyboardDrummer** [comment]
> Do others have thoughts on that?

Should we not first understand why we're getting warnings for the above proof, before adding an option to turn them off? I didn't find this explanation in the issue details.

**Comment by atomb** [comment]
Ah, I guess it wasn't explicit here because @alex-chew and I discussed it offline. We do understand what's going on. The specific example above is an intentional proof by contradiction, which will always give rise to warnings about proof using contradictory assumptions. Because such proofs are legitimate, we fundamentally need a way to indicate that they're intentional.

We could have something specific to the case of contradictory assumptions (marking something as an intentional proof by contradiction in some way). But we also want something for redundant assumptions that, for whatever reason, the developer decides they want to keep. And, while we're at it, I expect there are other warnings we may want to be able to disable on a local basis.

**Comment by keyboardDrummer** [comment]
> The specific example above is an intentional proof by contradiction, which will always give rise to warnings about proof using contradictory assumptions.

I thought it wouldn't produce warnings because you added an exception for `assert false` so that the `false` part is not marked unused, and the `by clause` of `assert false` doesn't get to rely on the result of `assert false`, so it's not marked as contradictory.

How come there's a contradictory warning in this case?

**Comment by keyboardDrummer** [comment]
> But we also want something for redundant assumptions that, for whatever reason, the developer decides they want to keep. And, while we're at it, I expect there are other warnings we may want to be able to disable on a local basis.

I hope I'm not being to cautious here, but I'd rather see this cases explicitly before adding features to cover them.

In C# for example, there's a warning you get when you call a method that returns a Task, and you do not await this task.

There's a C# feature added so you can avoid this warning, which is to assign to `_`, so it looks like `_ = ReturnsATask()`. Without this feature, users could get the same effect by adding a pragma that disables the warning, but I much prefer the `_ =` code because the warning disabling pragma does not feel super maintainable to me.

**Comment by atomb** [comment]
> > The specific example above is an intentional proof by contradiction, which will always give rise to warnings about proof using contradictory assumptions.
> 
> I thought it wouldn't produce warnings because you added an exception for `assert false` so that the `false` part is not marked unused even though the statement can not be reached, and I thought the `by` clause of `assert false` doesn't get to rely on the result of `assert false`, so it's not marked as contradictory.
> 
> How come there's a contradictory warning in this case?

Unfortunately, triggers make things complicated. It's possible to have a case where `assert B; assert false;` succeeds but `assert false;` on its own does not, because Z3 needs something in `B` to trigger a quantifier instantiation. However, the actual assertion is not part of the proof in this case because triggers are a way of controlling the search process, not part of the final proof produced. If you decide to instead write this `assert false by { assert B; }`, you wind up with the same problem. The surrounding context is already contradictory, but Z3 just can't prove that until it sees `B`. Once it sees `B`, it can prove that the context is contradictory and that `B` was therefore proved using contradictory assumptions. So, I think we fundamentally need a way to mark such assertions, which guide the triggering process to prove a contradiction, as things not to warn about when they're intentional.

**Comment by keyboardDrummer** [comment]
@atomb clear explanation! Thank you

> So, I think we fundamentally need a way to mark such assertions, which guide the triggering process to prove a contradiction, as things not to warn about when they're intentional.

Seems like a simple solution. If there is a more automatic one we can always introduce that later.
