### ISSUE TITLE
Standard libraries included twice

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#4858]
### Dafny version

latest-nightly

### Code to produce this issue

```dafny
// A.dfy. The dfyconfig.toml contains "standard-library=true"
module A {
  import Std;
}

// B.dfy
// That dfyconfig.toml contains "standard-library=true" and also include A.dfy
module B {
  import Std;
}
```

### Command to run and resulting output

```code
Try to verify in VSCode or CLI. Fail
```

### What happened?

Complaints that FileIO is imported twice. It's not practical to not have the standard library on either project.

Current workaround: use `import A.Std` instead of `import Std`

### What type of operating system are you experiencing the problem on?

Windows

**Comment by robin-aws** [comment]
The actual bug is simpler and more serious AFAICT: if I create a new project with a `dfyconfig.toml` file with `standard-libraries = true` and open the folder in the IDE, then change the project file (say adding a space), I get the same error.

Hovering over the `[options]` part reveals a strong clue:

<img width="720" alt="image" src="https://github.com/dafny-lang/dafny/assets/30840053/ca59de13-fb01-456e-b513-cba9a3c33a64">

I suspect that the LSP is adding the standard library doo files again on every update.
