### ISSUE TITLE
False cyclic dependency with datatype extending trait

### ISSUE THREAD

**Issue by ssomayyajula** [dafny-lang/dafny#4939]
### Dafny version

4.4.0

### Code to produce this issue

```dafny
// Trampoline.dfy

trait Program {
  method Compute() returns (r: Result)
}

datatype Result =
| Bounce(next: Program)
| Done()

datatype Trivial extends Program =
  Trivial()
{
  method Compute() returns (r: Result) {
    return Done();
  }
}

datatype Seq extends Program =
  Seq(left: Program, right: Program)
{
  method Compute() returns (r: Result) {
    var result := left.Compute();
    match result
    case Done() => r := right.Compute();
    case Bounce(next) =>
      var next' := Seq(next, right);
      assert next' is Program;
      return Bounce(next');
  }
}
```

### Command to run and resulting output

```code
dafny verify --type-system-refresh --general-traits:datatype Trampoline.dfy
```

### What happened?

The typechecker raises:

```
Trampoline.dfy(19,9): Error: because of cyclic dependencies among constructor argument types, no instances of datatype 'Seq' can be constructed
   |
19 | datatype Seq extends Program =
   |          ^^^
```

likely b/c of the self-reference in `Seq.Compute()` despite `Seq(Trivial(), Trivial())` because one such instance.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by ssomayyajula** [comment]
Looks like the resolver can't find a grounding constructor for `Seq`. In particular, the definition

```
datatype Seq  = Seq(left: Program, right: Program)
```

is also rejected.

**Comment by ssomayyajula** [comment]
The workaround I provided needs #4946 to be fixed.

**Comment by RustanLeino** [comment]
Regarding the grounding constructors: Dafny insists that every `datatype` has a grounding constructor, a check that was implemented about a year into the design of Dafny (when datatypes were added to the language, about 15 years ago). The thought then was that:

* the existence of a grounding constructor implies that the datatype is nonempty, and
* the existence of a grounding constructor justifies being able to use structural inclusion as a well-founded order

The first of these thoughts turns out to be wrong. For example, in

``` dafny
class NoInstances {
  constructor ()
    requires false
  {
  }
}

datatype D = D(n: NoInstances)
```

type `D` has a grounding constructor, yet the type `D` is empty (because there are no instances of `NoInstances`). Luckily, Dafny now understands the difference between nonempty and possibly empty types, so there's no problem.

The second of the thoughts above also seems not to be right. Structural inclusion is well-founded as long as every value of the datatype has a "finite structure". This has to do with how you construct values of the datatype (namely, having to supply the arguments to a datatype constructor at the time it's called), not whether-or-not you can construct any values. If you cannot construct any values, then the datatype is empty, so induction holds trivially.

So, insisting that every datatype have a grounding constructor seems misguided. It may catch some errors (like forgetting to declare `Nil` for `List`, or intending to declare a `codatatype` and accidentally leaving off the "`co`"). Therefore, changing the "no grounding constructor" from an error to a warning would seem better. (It would be fair to give a program a way to avoid the warning. This could be done by supporting an optional `witness` clause for datatypes, where `witness *` would say "I'm okay with the type being treated as possibly empty". By supplying an actual witness, like `Seq(Trivial, Trivial)` in the example above, one could also have a way to override the attempted search for a grounding constructor.)

If we change the error to a warning, we should also check that the compiler understands the type may be nonempty.

**Comment by selig** [comment]
I have run into the same error with the following code snippet

```
trait Interface {
  function getString(i: int) : string
}
datatype Wrapper extends Interface = Wrapper(inner: Interface)
{
  function getString(i: int) : string
  {
    inner.getString(i+1)
  }
}
datatype DetectZero extends Interface  = DetectZero
{
  function getString(i: int) : string
  {
    if i == 0 
    then "zero" 
    else "I don't know"
  }
}
function getWrappedDetectZero() : Interface 
{
  Wrapper(DetectZero)
}
```

I tried to work around this by seeing if Dafny would notice if I just wrapped up the nested `Interface` in a `Store` datatype.... but that didn't work as that simple `Store` still had the same above error

```
datatype Store = Store(thing: Interface)
```

My current workaround is to use something like an `extern` class for `Store` and hide the fact that we have an inner `Interface`. It looks something like this (but not exactly like this as my actual code is a bit more complex).

```
class {:extern} Store {
  var interface : Interface
  constructor(interface: Interface) { this.interface := interface; }
  function getResolver() : (res: Interface)
     ensures res == interface
}
datatype Wrapper extends Interface = Wrapper(inner: Store)
{
  function getString(i: int) : string
  {
    inner.getInterface().getString(i+1)
  }
}
```

This allows me to compile the code whilst manually providing `Store`. I'd much prefer it if the original code worked.
