### ISSUE TITLE
Incompleteness issue for an unreachable while loop

### ISSUE THREAD

**Issue by muchang** [dafny-lang/dafny#5012]
### Dafny version

4.4.0

### Code to produce this issue

```dafny
method main (a: int){
    var tmp := false;
    var i := 0; 
    while (a < a) {
        tmp := true;
        i := i + 1;
    }
    assert (! tmp);
}
```

### Command to run and resulting output

```code
$ ./Dafny test.dfy

test.dfy(8,11): Error: assertion might not hold 

Dafny program verifier finished with 0 verified, 1 error
```

### What happened?

For this program, the while loop condition is infeasible, thus the variable `tmp` should be `false` at the end of the program. Therefore, the program should be verified. However, Dafny reports an error. 

Removing `tmp := true;` makes this program able to be verified, but it is in fact unreachable code.  Changing `while` to `if` also solves the problem. 

It happens since 3.13.0. 

### What type of operating system are you experiencing the problem on?

Linux, WSL

**Comment by MikaelMayer** [comment]
A while loop is like calling a method, with a modifies clause that can be determined automatically. The guard test is part of the body of that method so it's not known from outside of the while loop if the body executed or not, the only thing that is known is what the loop might have modified and the invariants.

Knowing that, this incompleteness has a quick workaround:

```dafny
method main (a: int){
    var tmp := false;
    var i := 0; 
    while (a < a)
        invariant  tmp == false
    {
        tmp := true;
        i := i + 1;
    }
    assert (! tmp);
}
```

Feel free to close the issue if that answer your question, as it's likely that verification of while loop is not going to change because in general we don't want to try to prove that the condition is always false (trying to prove false could trigger slow verification). Otherwise, feel free to ask a follow-up question.

**Comment by muchang** [comment]
Thanks for your reply! It answered my question.

**Comment by muchang** [comment]
I am wondering whether there are some optimizations/simplifing for the constants. For example, the following program can be verified by changing `a` to `1`. 
```
method main (a: int){
    var tmp := false;
    var i := 0; 
    while (1 < 1) {
        tmp := true;
        i := i + 1;
    }
    assert (! tmp);
}
```

**Comment by atomb** [comment]
That's because that first invariant is not true after the loop has executed at least one iteration, but the second one isn't true at the beginning of the first iteration. One invariant that works is `invariant i > 0 ==> tmp == true`.
