### ISSUE TITLE
Major 4.4 verification regression

### ISSUE THREAD

**Issue by ajewellamz** [dafny-lang/dafny#5100]
### Dafny version

4.4

### Code to produce this issue

```dafny
https://github.com/aws/aws-database-encryption-sdk-dynamodb
branch ajewell/json
file : DynamoDbEncryption/dafny/JsonEncryptor/src/JsonToStruct.dfy
```

### Command to run and resulting output

```code
dafny verify --function-syntax:3 JsonToStruct.dfy

With 4.2, this verifies quickly
With 4.4, after an hour or so I get
`Prover error: Unexpected prover response (getting info about 'unknown' response): (:reason-unknown "��
v<^")`
```

### What happened?

I expected 4.4 to be no worse than 4.2

### What type of operating system are you experiencing the problem on?

Mac

**Comment by ajewellamz** [comment]
With 4.4, the above error is emitted, but the verification process continues.

**Comment by atomb** [comment]
I can confirm that this is still an issue with the latest development version.

**Comment by atomb** [comment]
And I've narrowed the problem down to first occurring with commit 6da881fe9eb3f388b986ab9d73e9e9c7035583b2, which changed the default approach to encoding problems in SMT. In general, this change made most verification significantly faster. However, that clearly isn't true for all code!

Unfortunately, adding `--boogie -typeEncoding:p` to the command line, to reverse that change in default, isn't sufficient to make things go quickly again. There have been other changes to the verifier in the meantime, since that change in the default, and they seem to also be affecting performance on this example.

**Comment by atomb** [comment]
I think the source of this problem is the non-linear arithmetic here:

https://github.com/aws/aws-cryptographic-material-providers-library/blob/main/StandardLibrary/src/UInt.dfy#L85-L93

I suspect that making that function opaque and proving some relevant properties about it in separate lemmas (if the existing lemmas aren't enough) could be very effective at reducing the problem. Removing the postcondition could also be helpful, though I'm sure it'll require some refactoring to do either.

You can see an example of some very similar code we've refactored to be much less brittle here:

https://github.com/dafny-lang/dafny/blob/master/Source/DafnyStandardLibraries/src/Std/Base64.dfy

That file was derived from this one:

https://github.com/aws/aws-cryptographic-material-providers-library/blob/main/StandardLibrary/src/Base64.dfy

**Comment by ajewellamz** [comment]
Making those functions opaque solved the problem. Many thanks.
