### ISSUE TITLE
Add syntactic sugar for specifying validity constraints on classes

### ISSUE THREAD

**Issue by keyboardDrummer** [dafny-lang/dafny#5168]
Enable writing

```dafny 
class Foo {
  reads this, Repr
  maintains P()
  maintains Q()

  constructor()
  method Bar()
  function Baz(): nat
  function Zomp(): nat
}
```

which gets desugared into

```dafny
class Foo {
  constructor()
    ensures P() && Q()

  method Bar()
    requires P() && Q()
    ensures P() && Q()

  function Baz(): nat
    reads this, Repr
    requires P() && Q()

  function Zomp(): nat
    reads this, Repr
    requires P() && Q()
}
```

A `reads <Expression>` declaration gets added to the reads clause of any function in the class.

A `maintains <Expression>` declaration gets added to the requires clause of any method or function in the class, and to the ensures clause of any method in the class.

**Comment by MikaelMayer** [comment]
I think what you might be interested in this attribute:

https://dafny.org/latest/DafnyRef/DafnyRef#sec-attributes-autocontracts

It also takes care of adding freshness properties of the new elements of `Repr` in the ensures clause, otherwise it becomes impossible to prove disjointness.

However, I haven't seen any adoption of this attribute, and I don't know exactly why. I only have a few insights to think why. I think local reasoning is the biggest challenge here, because until today, Dafny makes it feel that all the requirements of a method can be known by accessing the method itself, which is very convenient. If people want less specifications, they have the choice to refactor their pre/post conditions into predicates anyway.

A problem with that attribute and this proposal too is that you cannot define "private" methods that don't need the invariant, or you would have to invent a special syntax for that like "private" or "{:no-invariant}" which feel like too much. And such private methods are very convenient to off-load some inner work.

We could also introduce the notion of an invariant like a special predicate, that way we wouldn't have reads clauses that look like stand-alone member declarations:
```
class Foo {
  invariant predicate Valid()
    reads this, Repr
  {
    P() && Q()
  }
```
There is a good reason why you will probably want to name your invariant predicate if you only add maintenance conditions on pre/post condition: If, within a method, you call an external method which circles back to this object, you need to be able to provide the fact that the invariant of that object `Foo` holds when calling the external function.

I also discussed with @erniecohen about invariants and found out something interesting, is that if you require your invariant to be satisfied _for every assignment_, then 1) You can define invariants on classes without any methods 2) The invariant can be guaranteed to hold at any time. 3) Your "maintenance" invariant can just consist of `maintains innerInvariant` where `innerInvariant` is a boolean field that implies an inner invariant, so that it can be set to `false` when the invariant needs to be broken temporarily.

**Comment by MikaelMayer** [comment]
Heap-reading invariants would be especially useful in cases where we could hide the implementation, like here:
https://github.com/dafny-lang/rfcs/pull/14/files

**Comment by keyboardDrummer** [comment]
> A problem with that attribute and this proposal too is that you cannot define "private" methods that don't need the invariant. And such private methods are very convenient to off-load some inner work.

Good point! Thanks

> or you would have to invent a special syntax for that like "private" or "{:no-invariant}" which feel like too much. 

I agree, unless such a feature had other uses. I guess that should be part of this proposal then.

> If, within a method, you call an external method which circles back to this object, you need to be able to provide the fact that the invariant of that object Foo holds when calling the external function.

I'm not sure what you're describing. External in what sense? A method that's not part of this class? What do you mean by circles back to this object?

**Comment by MikaelMayer** [comment]
> > If, within a method, you call an external method which circles back to this object, you need to be able to provide the fact that the invariant of that object Foo holds when calling the external function.
> 
> I'm not sure what you're describing. External in what sense? A method that's not part of this class? What do you mean by circles back to this object?

Consider the following example:
```dafny
class TwoOppositeNumbers {
  invariant x + y == 0
  method Enter() modifies this { // Requires invariant and ensures invariant implicitly
    x := x + 1;
    Exit(this); // No requires of the invariant
    y := y - 1;
  }
  method EnterSecond() { // Requires invariant and ensures invariant implicitly
     if x  + y == 0 {
       print 1 / 0;
     }
   }
}

method Exit(s: TwoOppositeNumbers) modifies s {
  s.EnterSecond();
}
```
For this example, you would need to give specifications for the outside method `Exit` so that it would know that the invariant still holds, that's why I'd prefer to name the invariant because, like in the autocontracts attribute, the invariant might not hold at every point.

> > if you require your invariant to be satisfied for every assignment
> 
> Not sure what you mean by that. It sounds like you're saying, whenever you assign anything anywhere, check for all allocated objects that their invariants still hold, which seems intractable to me.

You got it: whenever you assign anything anywhere, check for all allocated objects that might read this object that their invariant still hold.
I had found a way out of that that I have not fully explored but it seems doable given the observation that such invariants have a reads clause, and that you could require that each of the objects being read should also contain the original object in their reads clause too. That would make it tractable and verifiable.
