### ISSUE TITLE
Enable reusing the specification of options in a dfyconfig.toml

### ISSUE THREAD

**Issue by keyboardDrummer** [dafny-lang/dafny#5337]
To enable reusing the specification of options, Dafny should allow using a Dafny project file as a source file, either directly on the CLI or in the `includes` section of a project file. This allows specifying a tree of project files. Elements from this tree are merged into a single Dafny project. The merging is done bottom up, where later elements override the options set by earlier ones. Overriding an excludes can be done by setting the same path in an includes. 
  - A positive side-effect of this change is that there no longer is a special treatment for the first file that is passed to the CLI, since previously only that could be a project file.

**Comment by robin-aws** [comment]
This sounds useful! I initially thought we wouldn't need both this feature and https://github.com/dafny-lang/dafny/issues/5336 since they behave similarly, but I think the use cases are pretty different: organizing similar groups of code internally in a project, as opposed to dependencies between projects that may be maintained by independent groups of people.

I'd suggest if we implement this we deprecate the `{:options ...}` attribute, since a co-located project file seems like a much cleaner and flexible solution.

**Comment by keyboardDrummer** [comment]
I should clarify. The intended usage here is:

```
/src/sharedOptions.dfyconfig.toml
/src/shared/dfyconfig.toml <- includes `sharedOptions.dfyconfig.toml`
/src/java/dfyconfig.toml <- includes `sharedOptions.dfyconfig.toml`, depends on `shared/dfyconfig.toml`
/src/rust/dfyconfig.toml <- includes `sharedOptions.dfyconfig.toml`, depends on `shared/dfyconfig.toml`
```
