### ISSUE TITLE
Flaky test: ConcurrentCompilationDoesNotBreakCaching 

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#5515]
Seen here: https://github.com/dafny-lang/dafny/actions/runs/9323403744/job/25666501002?pr=5513

```dafny
[xUnit.net 00:09:09.00]       Assert.Equal() Failure
[xUnit.net 00:09:09.00]       Expected: 2
[xUnit.net 00:09:09.00]       Actual:   3
[xUnit.net 00:09:09.00]       Stack Trace:
[xUnit.net 00:09:09.00]         /Users/runner/work/dafny/dafny/dafny/Source/DafnyLanguageServer.Test/Synchronization/CachingTest.cs(415,0): at Microsoft.Dafny.LanguageServer.IntegrationTest.Synchronization.CachingTest.ConcurrentCompilationDoesNotBreakCaching()
```

**Comment by atomb** [comment]
I've dug into this one a little, and it's a bit unclear to me what it really should be testing. It's clear to me that it's confirming that there are at least some cache hits after modifying an already-loaded document. Is testing that there are exactly the same number after a bunch of changes too strict, though? Is it sufficient that the number of misses is close in the `before` and `after` cases, even if not exactly equal?

**Comment by keyboardDrummer** [comment]
> It's clear to me that it's confirming that there are at least some cache hits after modifying an already-loaded document.

It's testing that the unchanged files hit the parsing and resolution cache a 100% of the time, by checking that there are no additional misses in those unchanged files, after making changes to another file:

```c#
    Assert.Equal(before1.ParseMisses, after1.ParseMisses);
    Assert.Equal(before1.ResolutionMisses, after1.ResolutionMisses);
    Assert.Equal(before2.ParseMisses, after2.ParseMisses);
    Assert.Equal(before2.ResolutionMisses, after2.ResolutionMisses);
```

**Comment by keyboardDrummer** [comment]
> [xUnit.net 00:09:09.00]       Assert.Equal() Failure
> [xUnit.net 00:09:09.00]       Expected: 2
> [xUnit.net 00:09:09.00]       Actual:   3

It's curious that it has two misses to begin with, since those files never get updated. I think what happens, is that because it opens several files, where only the fourth file is a project file, initially the first three files all start separate compilations, and these concurrently start parsing the same file, so there are multiple cache misses.

The `Wait` part in the following line ensures that the compilation currently owning `imported` has finished parsing and resolving:
```
    var before1 = await WaitAndCountHits(imported1);
```

The test failure implies that after the above line, there's still a parse miss for `imported1`. I don't understand how that's possible, since after waiting for `imported1`, its parsing/resolution should already be in the cache.

Anyways, moving the line `var project = CreateOpenAndWaitForResolve("", Path.Combine(temp, "dfyconfig.toml"));` so that this is the first file the be created, causes all opened files to be placed under the same project manager, so there are fewer compilations running at a time. Debugging shows this changes makes its so `before1` only has 1 parse miss, and I think it's likely to stabilize the test.

The concurrent part in the name of the test just refers to the changes being applied without waiting, which causes a new compilation to be run while the old one is being cancelled:

```
    for (int i = 0; i < 100; i++) {
      ApplyChange(ref importer, new Range(0, 0, 0, 0), "// added this comment\n");
    }
```
