### ISSUE TITLE
C++ backend for Dafny

### ISSUE THREAD

**Issue by parno** [dafny-lang/dafny#563]
For a couple of projects that we're involved with here at CMU, we've been building a C++ backend of Dafny on a fork of the repository.  I wanted to open this issue as a place to discuss when/how best to contribute it back to mainline Dafny.

At this point, the backend is robust enough that we can compile and run large Dafny developments, e.g., a complex network protocol implementation and a large file system.  However, the backend was written assuming that it would primarily support writing C/C++ style code in Dafny, which leads to some limitations in the current implementation.  For example, it does not support compiling mathematical integers, on the assumption that including such integers in a C development is a performance bug.  Similarly, it does not support more advanced Dafny features like traits.  As a result, we do not compile most of the existing Dafny compiler test suite but rather developed our own suite of compiler test cases.  The current backend also assumes the use of C++17 in order to cleanly and performantly implement datatypes.

If, despite these limitations, it still seems like something that would be useful to merge in, I'm open to suggestions on how to go about it.  The easiest for me would be to submit one giant PR that includes a few (minor) modifications to the generic compiler plus the new `Compiler-cpp.cs` file and accompanying test suite, but if you have suggestions for an alternate way to structure such a PR, please let me know.

**Comment by RustanLeino** [comment]
Hi Bryan,

Wonderful! I suggest proceeding in the following way:

0. Make a PR for the changes needed to existing code (that is, without adding the C++ target compiler).
1. Make a big PR that adds C++ as a target backend. Explain in the PR the differences you mention here (and anything else you think of), and add a brief notice in the `/help` message that not everything is supported. 
2. Continue contributing code as you would. For example, if most of the compiler tests fail because of not supporting mathematical integer, consider adding this support and also adding a command-line switch that, for _all_ the compiler backends, unsoundly turns unbounded integers into a specified :nativeType.

  Rustan

**Comment by parno** [comment]
Thanks, this sounds like a solid plan.  I'll work on putting it into action once we've navigated the current shift to online-only education.

**Comment by parno** [comment]
Okay, step 0 above is now available as PR #586.

**Comment by parno** [comment]
Step 1 (the big PR) is now available as PR #702.

**Comment by robin-aws** [comment]
Exciting!! I see that it's soft-blocked on #680, but I'm working on finishing that now and will try to get it in ASAP.

**Comment by acioc** [comment]
Closing since https://github.com/dafny-lang/dafny/pull/702 was merged. 

Let's create separate (new) issues for follow up steps so we can track this a bit better.
