### ISSUE TITLE
Emit Rust code

### ISSUE THREAD

**Issue by johnterickson** [dafny-lang/dafny#601]
Rust is a particularly interesting language to interop with Dafny because of it's strong types, anti-aliasing guarantees, memory safety, and performance optimizations.

An example of how this could light up well is if Dafny could turn `expect` #547 expressions into compiler optimization hints. Here's the a Rust version of the binary search example that I wrote by hand:
```
pub extern fn binary_search(a: &[i32], key: i32) -> Option<usize> {
    let mut lo = 0;
    let mut hi = a.len();
    while lo < hi {
        let mid = lo + (hi - lo) / 2;

        // expect mid < |len|;
        if !(mid < a.len()) { unsafe { unreachable_unchecked(); } }

        if key < a[mid] {
            hi = mid;
        } else if a[mid] < key {
            lo = mid + 1;
        } else {
            return Some(mid);
        }
    }

    return None;
}
```

The resulting code (at least via MSVC) contains no bounds checks for `a[mid]` when the (faked) expect clause is included - cool!

**Comment by robin-aws** [comment]
I responded on #547, but then realized we can actually do better than your example! 

Because the Dafny verifier requires all array indexes to be provably safe, we should be able to compile all Dafny array operations to *unsafe* Rust array operations, since Dafny is already responsible for the bounds checking. There's a version of binary search in the Dafny test suite here that doesn't need `expect` to verify and therefore wouldn't have the indirect bounds check either: https://github.com/dafny-lang/dafny/blob/14c5be902cea21eb994f3e0530200d881f9ce5bc/Test/dafny4/BinarySearch.dfy#L55-L76

`expect` is useful for situations where you can't or don't want to statically guarantee an assertion holds, but in most cases like this one it's not necessary.

**Comment by MikaelMayer** [comment]
In the current development of the Dafny to Rust code generator, arrays will be encoding using slices and accesses will be using unchecked access. So I'm happy to close this issue !
Note that we might want a debugging mode in which we encode arrays using vec just in case the code does not pass verification, to remain somehow memory safe, but it's not planned as of today.

**Comment by MikaelMayer** [comment]
Let me leave it open until the branch is merged into master

**Comment by MikaelMayer** [comment]
The branch has been merged to master, so native arrays are now available. Note that you get full performance of such arrays if you use --raw-pointers.
