### ISSUE TITLE
Compiled code initializes datatype fields with wrong default values

### ISSUE THREAD

**Issue by Chris-Hawblitzel** [dafny-lang/dafny#610]
[cf #674]

In the following code, Dafny can prove that the variables `x`, `a`, and `b` are all greater than 0:

```
type pos = i:int | i > 0 witness 1
 
method m()
{
  var x:pos;
  assert x > 0;
  var p:(pos, pos);
  var (a, b) := p;
  assert a > 0;
  assert b > 0;
}
```

However, in the generated C# code, `a` and `b` are 0, which would violate the assertions in the Dafny code:

```
public static void m()
{
  BigInteger _22_x = pos.Witness;
  { }
  _System.Tuple2<BigInteger,BigInteger> _23_p = _System.Tuple2<BigInteger,BigInteger>.Default;
  _System.Tuple2<BigInteger,BigInteger> _let_tmp_rhs0 = _23_p;
  BigInteger _24_a = ((_System.Tuple2<BigInteger,BigInteger>)_let_tmp_rhs0)._0;
  BigInteger _25_b = ((_System.Tuple2<BigInteger,BigInteger>)_let_tmp_rhs0)._1;
  { }
  { }
}
```

**Comment by parno** [comment]
FWIW, the proximate cause of the bug appears to be this line in the C# backend:

https://github.com/dafny-lang/dafny/blob/master/Source/Dafny/Compiler-Csharp.cs#L1042

is processing the “DatatypeDecl” for Tuple, but it’s calling `TypeNames` on the TypeArgs, which calls `TypeName`, which starts (https://github.com/dafny-lang/dafny/blob/master/Source/Dafny/Compiler-Csharp.cs#L877) by calling NormalizeExpand, which converts pos into int.  Hence, we get `_System.Tuple2<BigInteger,BigInteger>.Default` instead of `_System.Tuple2<pos, pos>.Default`.

**Comment by davidcok** [comment]
Failing for c# at runtime, not for other languages.
