### ISSUE TITLE
Dafny 1.9.8 for Ubuntu zip file

### ISSUE THREAD

**Issue by gconnell** [dafny-lang/dafny#66]
A few issues:

1) Dafny.exe and dafny script not marked executable
2) dafny script has windows newlines, causing issues:

```
gconnell@tinyduck:~/dafny$ bash -x dafny
+ $'\r'
dafny: line 2: $'\r': command not found
++ which mono
+ MONO=$'/usr/bin/mono\r'
++ dirname dafny
+ DAFNY=$'./Dafny.exe\r'
+ $'\r'
dafny: line 5: $'\r': command not found
dafny: line 17: syntax error: unexpected end of file
--- Exit code 2 @ Mon Jan 16 21:34:04 MST 2017 ---
```

Running `dos2unix dafny/dafny` fixes issue 2, `chmox u+x` fixes issue 1

**Comment by dyschwartz** [comment]
Same 2 problems with v1.9.8 for Mac OS X

**Comment by cpitclaudel** [comment]
Indeed, I see it too. @RustanLeino, can you check your git settings? Could it be that your git is set up to convert newlines?

**Comment by danmatichuk** [comment]
The git repository is set up to convert line endings to LF, and indeed in
the repository the execute bit is set on that script and has LF line
endings. I believe Rustan's local setup has autocrlf setup, which keeps
CRLF line endings in the local copy, but LF line endings when checking in.
What we're seeing is the results of Windows Git trying to be amenable to a
Windows environment.

There are a few ways around this, but my suggestion would be that the
releases could be made by downloading the source archive from Github,
rather than zipping a local git checkout.

**Comment by cpitclaudel** [comment]
@danmatichuk That sounds reasonable, and in line with suggestion above; I'm not sure about the edit, though: the zips are (should be?) produced with the release script at https://github.com/Microsoft/dafny/blob/master/package.py, and https://github.com/Microsoft/dafny/blob/master/package.py#L144 should set the executable bit explicitly, actually.  I wonder what went wrong.

**Comment by fefrei** [comment]
This issue still exists with release 1.9.9.

**Comment by cpitclaudel** [comment]
Ping @RustanLeino ; Rustan, how do you create zip releases ?

**Comment by seanmcl** [comment]
Over 2 years old.
