### ISSUE TITLE
Fix Boogie submodule url

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#878]
I'm assuming it wasn't intended to point to keyboardDrummer/boogie :)

https://github.com/dafny-lang/dafny/blob/master/.gitmodules#L3

**Comment by keyboardDrummer** [comment]
Well.. it's not entirely unintentional. It is pointing to a fork of Boogie v2.4.21 that removes GitVersionTask from the boogie projects. GitVersionTask has trouble with submodules, since it requires the git repository not to headless in order to build, while git submodules are checked out headless. GitVersionTask also has a build issue that requires environment variable to be set [ref](https://github.com/boogie-org/boogie/blob/master/.travis.yml#L15). All in all it's better not to have GitVersionTask in the Boogie that Dafny builds.

Note that I've added a tag to the fork commit so it doesn't get lost.

Also I'm trying to move to consuming Boogie through NuGet, which these PR:
https://github.com/boogie-org/boogie/pull/291
https://github.com/dafny-lang/dafny/pull/876

**Comment by robin-aws** [comment]
Fair enough. Definitely want to keep this issue open to flag the need to fix the temporary solution then! 👍 

Thanks for pushing on getting the Boogie packages into NuGet: big +1 from me on that!

**Comment by RustanLeino** [comment]
Done, PR https://github.com/dafny-lang/dafny/pull/974.
