### ISSUE TITLE
uninitialised arrays still usable

### ISSUE THREAD

**Issue by davidstreader** [dafny-lang/dafny#884]
Not sure if this is intentional or  minor bug. But an uninitialized array holds a value that can be printed, used in an expression, used in conditional statements but not  as an index to an array.  

```
method Main() {
     var b := new int[10];
     var x:int := b[0] +1;
     print "x = ",x,"\n";
     //var n:int := b[x];   // index out of range
     //assert x == 1;       // assertion violation
     if (x==1) {print"What about the assertion\n";}  
}
```

**Comment by RustanLeino** [comment]
This is intentional, not a bug. Being a type-safe language, Dafny guarantees that every access of a variable (local variable, parameter, field, array elements, ...) gives a value of the variable's type. For some types (like `int` in your example), this can be done without further assistance from the program. For other types, Dafny requires help from the program and will issue an error.

Examples: In your example, the statement

    var b := new int[10];

is guaranteed to give you a freshly allocated array with 10 elements, each element having the value of some `int`. Since each element can be any `int` whatsoever, the verifier will not be able to prove anything more specific. Had the array-element type instead been `nat`, for example, then you are guaranteed that every array element of the array is a non-negative integer:

    var b := new nat[10];
    assert 0 <= b[5];

If you try to allocate an array of non-null references, then you will get an error message, because Dafny doesn't claim to know how to initialize those for you:

    var b := new MyClass[10];  // error: you need to give an initializer

If you want to initialize the array elements yourself when you allocate the array, you can give an initializer, which is a function from each index to the initial value you want:

    var b := new int[10](i => 5*i + 3);
    assert b[2] == 13;

**Comment by davidstreader** [comment]
Thanks - I am not trying to be awkward for the sake of it. But I know students will press me on these issues.
So I am unsure what the state of a nat variable that is uninitialised is.  The following example is contrived but highlights my concern:
```
method  getMe(a:array<nat>, i:nat) returns (r:nat) 
    requires a.Length == 10 && i == 0
    {  r:= a[i]; }
method Main() {
     var b := new nat[10];
     var c := new nat[10](i=>66 -(3*i));
     //var fail := getMe(c,b[1]);   //b[1]==0  Fails
     if (b[1]== 0 ) {print"c[b[1]]= ", c[0], "\n";}       
}
```
 
The distinction between the two evaluations of ```b[1]==0```  is worrying. And I am not sure why the if guard  ```b[1]==0```  can be evaluated but not the requires clause. Would it not be safer  to disallow both.

**Comment by kjx** [comment]
After a rant in David's office - the point is that there are at least two design choices here.
- whether Dafny surfaces its notion of uninitialised to programmers
- whether there's a difference between an uninitialised value vs a value Dafny doesn't know
- whether Dafny's operational semantics permits unspecified behaviour.

Clearly complex programming patterns (viz lazily initialised arrays) can surface uninitialised, but e.g. a ghost assertion "initialised(x)" would make those kind of specifications much easier to follow.   Translating to C, though, will inherit undefined behaviour into Dafny programs. Dafny's array bounds rules prevent one kind of undefined behaviour, but reading uninitialised values is another kind that isn't prevented. 

We have to explain this to 90 students in about 90 minutes...

**Comment by robin-aws** [comment]
It probably makes the most sense to disallow this kind of non-determinism using the `/definiteAssignment` flag in your case.

**Comment by RustanLeino** [comment]
Everything you can access in Dafny has a value of its type. If you have specified what that value is, then that's what the value is (e.g., `x := 3` sets `x` to exactly the value 3, and the precondition `i == 0` says `i` is exactly 0). If you have specified some properties of the value, then you know the value is a value of the type that satisfies those properties (e.g., `x < 2000` says that the value of `x` is less than 2000, but you don't know what value less than 2000, and `a.Length == 10` says that the length of the array reference by `a` is 10 but says nothing about the specific values of its elements). If you haven't specified at all what the value is, then all the verifier knows is that the value is a value of its type (e.g., after the allocation of the array referenced by `b`, you know nothing about the values of the elements of `b` except that each one is a `nat`).

I'm afraid I don't understand David's question, but perhaps this address it: If you test a value, like in David's `if b[1] == 0 ...`, then you know that the "then" branch of that `if` statement will be taken only if `b[1] == 0` holds, and you know that the "then" branch will _not_ be taken if the condition does not hold. There's no demand that the guard of an `if` statement always evaluates to `true`. Indeed, you use an `if` statement in a program because you don't know if the guard will evaluate to `true` or `false`, and you'd like the program to do different things depending on that outcome. A `requires` clause is different. A `requires` clause gives a precondition, and a precondition must always hold on entry to the method. The verifier enforces this. If the verifier cannot prove that the precondition holds, then it will complain. Because the verifier always enforces that the preconditions at `true` at a call site, there's no need to include them at run time--they would always evaluate to `true` anyway. Preconditions are _ghost_, which is to say that they are not present at run time.

I'm getting the impression that you're confusing yourselves by running the programs and printing values. Sometimes this can help. But you have to remember that what you see at run time is only one possible execution that follows all the rules that the type checker and verifier enforce. So, for example, if you run David's program above and you observe that `b[1]` is 0 in `Main`, that doesn't mean you can prove that. The next time you compile or run the program, that value may be `8` or `127`. In a similar way, if you print the value of `a[3]` inside `getMe` in David's program, you will see the value `57`. But an assertion

    assert a[3] == 57;

inside `getMe` is not going to verify, because all that is known about the value of `a` in `getMe` is that `a` is a reference to an array of length 10, each of whose elements is some non-negative integer.

**Comment by RustanLeino** [comment]
To @kjx 's specific questions:

* In a legal Dafny program, there is no notion of uninitialized. If a program doesn't explicitly initialize something, then the compiler will find an arbitrary value (of the appropriate type) if possible. If the type is such that the compiler doesn't can't easily fill in the value, then you will get some complaint from the tool (such complaints will typically say something about "definite assignment").

* It often happens that the value of something is underspecified, which is what I think you mean by "a value Dafny doesn't know". This is legal, but you won't be able to prove very much about the value.

* Yes, the Dafny language allows nondeterminism. (As @robin-aws alluded to, you can turn off all nondeterministic features using `/definiteAssignment:3` from the command line.)

All array initialization in Dafny is eager. There is no lazy array initialization.

I think what you're saying about compilation to C assumes the Dafny compiler doesn't do much. But the compiler is working hard to make sure everything you verify about your program is really true. For example, if you have a type

    type RoomTemperature = c | 18 <= c < 30 witness 20

and a program snippet

    var y: RoomTemperature;
    print y, "\n";

then the compiler will initialize `y` to some value in the type `RoomTemperature`. So, the printed value will be some value between 18 (inclusive) and 30 (exclusive). The C language doesn't have particularly expressive types, so you can't define the type `RoomTemperature`. If you did it manually in C, you'd probably use an `int`. In the C program snippet

    int x;
    printf("%d\n", x);

there's no reason to think the value printed would be in the range 18 to 30. Luckily, Dafny is not C. Dafny is type safe and also has a verifier.
