### ISSUE TITLE
The recursive parameter is not increasing while calling constructor of the datatype

### ISSUE THREAD

**Issue by roxanaluca** [dafny-lang/dafny#890]
Hello.
I have been trying to do modulo operation on the natural function which is declared as datatype. I realised that one of my parameter is not increasing because in the IDE shows to add decrease annotation for all parameters of the _moduloSubtract_ function.
Here is my code
```
datatype Nat = Zero | Succ(pred:Nat)

inductive predicate Lt(m: Nat, n: Nat)
{
   (m == Zero && n.Succ?) || (m.Succ? && n.Succ? && Lt(m.pred, n.pred))
}

function moduloSubtract(m:Nat, dif:Nat, n:Nat) : Nat
requires n.Succ?
{
    match m
    case Zero => dif
    case Succ(m') => 
      if Lt(Succ(dif),n) then
        moduloSubtract(m',Succ(dif),n)
      else moduloSubtract(m',Zero,n)
  }

  function moduloN(m: Nat, n: Nat) : Nat
  requires n.Succ?
  {
    moduloSubtract(m,Zero,n)
  }

  lemma testModulo(n:Nat)
  ensures n.Succ? && n!=Succ(Zero) ==> (moduloN(Succ(n),n) == Succ(n))
  {
  } 
  
  lemma testModuloZero(n:Nat)
  ensures n.Succ? ==> Lt(moduloN(Succ(Zero),n),n)
  {
  }

  lemma testLt(m:Nat,n:Nat)
  requires n.Succ?
  ensures Lt(moduloN(m,n),n)
  {
  }
  
 ``` 
I look forward to your reply as soon as possible.
Many thanks

**Comment by RustanLeino** [comment]
I think the message you're seeing from the IDE is not an error, but only an informational message. If you see a red squiggly underline (in VS Code), then that's an error. A green squiggly underline is just an informational message. Unfortunately, the green underlines are very conspicuous in the IDE, so they often get confused with errors.

(In my editor, I change the bold green color of informational messages to a color that is much more subtle. You can do that in VS Code by going to Settings, then searching for "workbench.color", clicking "Edit in settings.json", and then adding

```
    "workbench.colorCustomizations": {    
        "editorInfo.foreground": "#004040"
    }
```

or whatever other color you choose.)

If you turn on the Problem pane in VS Code, you should also see indications there that say if a message is an error or just information.

The reason you're getting these messages is that Dafny is informing you of what termination metric it used to prove termination. You don't need to do anything, unless it says it cannot prove termination (in which case you would need to supply an explicit `decreases` clause).

Your example does result in three error messages, because the Dafny verifier is not able to prove any of the three lemmas. You need to fill in proofs for those.

Finally, a suggestion: You have declared `Lt` to be an `inductive predicate`. Such an `inductive predicate` is an advanced feature that lets you indicate the least fixpoint of a recurrence relation (see https://easychair.org/publications/download/vHsB). You don't need that for your example (since the recursive call to `Lt` is verified to be terminating). Therefore, I would strongly recommend that you declare `Lt` to be just a `predicate` (not an `inductive predicate`).
