### ISSUE TITLE
Support the old URL to the PDF of the reference manual

### ISSUE THREAD

**Issue by wilcoxjay** [dafny-lang/dafny#891]
I am responsible for creating many links around the internet over the years to the URL `https://github.com/dafny-lang/dafny/blob/master/Docs/DafnyRef/out/DafnyRef.pdf`, which used to host a PDF of the reference manual. Is there any chance we make the build system put a copy of the new reference manual in PDF format at that location?

**Comment by davidcok** [comment]
I've committed a current copy of the RM at the requested location. Still to do is to modify the build procedure to update the committed RM when builds are released. (We don't commit the generated pdf on a frequent basis because it would add a lot of large files into git)

Note that a current version of the RM is always available through the html links.

**Comment by wilcoxjay** [comment]
ok, thanks!

**Comment by davidcok** [comment]
Edited the documentation pages to include this permanent URL. Also the release procedure to build the RM and copy it to this location.

**Comment by wilcoxjay** [comment]
awesome, thanks David!
