### ISSUE TITLE
Definition of an inconsistent `const` can lead to unsound verification results

### ISSUE THREAD

**Issue by franck44** [dafny-lang/dafny#922]
I am sorry for the title that may not be very precise but the following issue (seems to be a bug) 
requires a non-trivial set-up.

# Issue 1:  Inconsistent const definition disables checks of constraints in subsequent definitions.
Assume the following file `const.dfy` that defines some types and const:
```dafny
module FOO { 
    // seq with more than one element
    type L = x : seq<int> | |x| >= 1 as int witness [1]
    
    // a datatype using the previous type
    datatype D = D( xl : L)

    /** This const should not be allowed.  */
    // const KK := D([])    // label: FaultyConstDef 

    /** Another type definition. */
    datatype O = O(x : nat)

    /** This should not be allowed. */
    const OO := O(-1)
   
    // function method bar2() : int
    //     ensures false 
    // {
    //     0
    // }
    
 }
```
Running 
```bash
dafny.exe  /dafnyVerify:1 /compile:0 /tracePOs /traceTimes /noCheating:0 bug-reports/const.dfy
```
results in
```bash
Verifying CheckWellformed$$FOO.L ...
  [1 proof obligation]  verified

Verifying CheckWellformed$$FOO.__default.KK ...
  [1 proof obligation]  verified

Verifying CheckWellformed$$FOO.__default.OO ...
  [1 proof obligation]  verified

Dafny program verifier finished with 3 verified, 0 errors
```
On the other hand commenting out the `FaultyConstDef` line reveals the error in `OO` (as expected):
```bash
Verifying CheckWellformed$$FOO.__default.OO ...
  [1 proof obligation]  error
bug-reports/const.dfy(15,18): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0

Dafny program verifier finished with 1 verified, 1 error
``` 

# Issue 2: Including the module with the inconsistent const definition in another module leads to unsound verification results
If the previous module `FOO` is included/imported in another one as exemplified in the file `importFoo.dfy`:
```dafny
include "./const.dfy"

module BAR {

    import opened FOO

    function method bar() : int
        ensures false 
    {
        0
    }

}
```
running the verification on `importFoo.dfy` yields:
```bash
dafny.exe  /dafnyVerify:1 /compile:0 /tracePOs /traceTimes /noCheating:0 bug-reports/importFoo.dfy
Verifying CheckWellformed$$BAR.__default.bar ...
  [1 proof obligation]  verified

Dafny program verifier finished with 1 verified, 0 errors
```
and we have proved `false` :-( .
Commenting out the definition of `KK` (in `FOO`) does not change the output (because `OO` is still inconsistent).
However, commenting out both `KK` and `OO` reveals the error in `importFoo.dfy`
```bash
Verifying CheckWellformed$$BAR.__default.bar ...
  [1 proof obligation]  error
bug-reports/importFoo.dfy(7,20): Error BP5003: A postcondition might not hold on this return path.
bug-reports/importFoo.dfy(8,16): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    (0,0): anon4_Else

Dafny program verifier finished with 0 verified, 1 error
```
where the referenced post-condition is `ensures false`.

Note that this behaviour (unsound proof of false) does not appear when verifying a version of `const.dfy` with the same function (`bar2`) directly included in `const.dfy`.

# Initial investigation

1. issue 1: the problem seems to stem from the definition of inconsistent `const` involving types with constraints, 
2. it seems like the inconsistent definition has some future effect on other errors that can occur in other const definitions (e.g. the inconsistency of `OO` is not flagged when the previous inconsistent `KK` is defined)
3. issue 2: accross modules, it seems like inconsistent definitions (`KK` or `OO` alone) may has some side effects on the soundness of verification results in modules **including the faulty one** (e.g. we can prove the post-condition `false` function `bar` in module `BAR` that imports faulty module `FOO`). 

# Work around
Don't define inconsistent consts ... easier said than done.
And I did it ... but later found out some inconsistent results in other modules.

# Dafny versions impacted
Occurs in the following versions on MacOSX:
* Dafny 3.0.0.20817
* Dafny 2.3.0.10506

# How discovered
The problem occurred in a more complicated setting in [this project](https://github.com/PegaSysEng/eth2.0-dafny) and was trimmed down to a shorter version.

**Comment by RustanLeino** [comment]
Issue 1 is a bug. It is a soundness bug, because you can prove false in a context that includes `OO`.

The presence of the bug in module `FOO` masks the error in module `BAR`. Moreover, if only `importFoo.dfy` (and not also `Foo.dfy`) is mentioned on the command line, then--by design--the contents of `importFoo.dfy` (which is `include`'d, but not listed on the command line) is not verified but just assumed. For this reason, _no_ error is reported in Issue 2. Perhaps we could improved this by outputting an informational message about this. There is also a command line switch, `/verifyAllModules`, which says also to verify files that are `include`d.

**Comment by robin-aws** [comment]
Also relevant, since it would allow the `dafny` CLI to know whether an included file was successfully verified previously: https://github.com/dafny-lang/dafny/issues/927

**Comment by franck44** [comment]
> The presence of the bug in module FOO masks the error in module BAR. Moreover, if only importFoo.dfy (and not also Foo.dfy) is mentioned on the command line, then--by design--the contents of importFoo.dfy (which is include'd, but not listed on the command line) is not verified but just assumed. For this reason, no error is reported in Issue 2. Perhaps we could improved this by outputting an informational message about this. There is also a command line switch, /verifyAllModules, which says also to verify files that are included.

Thanks for your quick reply. Sorry, I may have got it wrong but I don't understand some part of the previous explanations :-(
Should it be "the contents of **`Foo.dfy`**(which is include'd, but not listed on the command line) is not verified but just assumed"?
In that case, the problem you mention does not seem to be the one I reported in issue 2.

In issue 2, we can prove `false` in `BAR` when the module `FOO` **included** in `BAR` has the erroneous definition of `const` (e.g. `OO`).
So when `OO` or `KK` is ill-defined, if I run 
```bash
dafny.exe  /dafnyVerify:1 /compile:0 /tracePOs /traceTimes /noCheating:0 bug-reports/importFoo.dfy
```
no error shows up, and I believed there should have been one: one post-condition is not true (`false`).
But when `FOO` has no ill-defined `const` the same command correctly displays the violation of the post-condition `false`.
Overall, the non-verified module `FOO` included in `BAR` seems to have an impact on the soundness of the 
the verification on functions defined in `BAR`. 
If I understand well, the verification results for `importFoo.dfy` should not depend on the verification status of the included module `FOO`. Issue 2 that I reported shows the opposite I believe.

**Comment by RustanLeino** [comment]
Yes, sorry about my confusing typo. I did indeed mean "the contents of **Foo.dfy** ...".

**Comment by RustanLeino** [comment]
The design around files on the command line is as follows.

To verify a program, we want to be able to give Dafny a "closed" set of files, which I will call `AllFiles`, meaning a set of files where every symbol mentioned is declared somewhere. We also want to identity a subset `ToBeVerified` of `AllFiles` that are the files to be verified. In other words, the files `AllFiles - ToBeVerified` will not be verified, but are files needed to provide declarations for things that are mentioned elsewhere in `AllFiles`.

I will refer to the set of files `AllFiles - ToBeVerified` as `AssumedCorrect`. So, `AllFiles` is the union of `AssumedCorrect` and `ToBeVerified`.

To make it easier to give the sets `AllFiles` and `ToBeVerified` to Dafny, there is an `include` mechanism. I think of `include` as a _directive_ that helps the Dafny command-line tool, rather than that `include` is part of the Dafny language itself. (Similarly, the concept of a "file" is really a notion used by the command-line tool, whereas the Dafny language is in terms of `module`s.) The way to tell Dafny about `ToBeVerified` is to list the files in `ToBeVerified` on the command line. Dafny then reads those files, looks at any `include` directives in those files, reads those `include`d files and looks at their `include` directives, etc, until every file on the command line or mentioned (transitively) in some `include` has been read. This total set of files is `AllFiles`. In other words, `AllFiles` is the set of files you get from `ToBeVerified` by transitively following `include` directives.

So, Dafny will read all files that are listed on the command line and it will also read any file that it finds by following `include` directives, but it will _verify_ only those files that are listed on the command line. In terms of the sets I defined above, Dafny will read `AllFiles`, but it will only verify the files in `ToBeVerified`.

When verifying the files in `ToBeVerified`, the verifier will use the definitions in `AllFiles` -- including the definitions in `AssumedCorrect`, which are not verified. This means that if the verifier discovers some logical inconsistency in `AssumedCorrect`, then it will verify everything in `ToBeVerified` trivially. Moreover, since it's not verifying the files in `AssumedCorrect`, no error messages will be produced for those logical inconsistencies, either. (But if you ever list the files in `AssumedCorrect` on the command line, then the verifier will discover any errors among those files.)

Note that the verifier uses the definitions in `AssumedCorrect` without knowing if those definitions are consistent or not. To determine if there are any inconsistencies in `AssumedCorrect`, the verifier would have to verify those files as well. The rationale behind this design is that it lets you decide which files to verify. If every file you author has `include` directives that say which other files they depend on, then for any combination of your files, you can quickly put those files on the command line and get just those files verified -- the `include` directives will tell the tool what other files need to be read. And if, for example, you call `dafny A.dfy` for every file `A.dfy` that makes up your program (that is, one command-line invocation per file), the total effect will be that you have verified the entire program. More precisely, if calling Dafny on each file individually gives you no errors, then the entire program is correct.

The last sentence I wrote assumes there are no bugs in the verifier. Your Issue 1 above shows a bug in the verifier -- it should have flagged `KK` as an error, but this check is apparently missing (we'll get that fixed).

In your Issue 1, `AllFiles` and `ToBeVerified` are the singleton set `{Foo.dfy}`. In your Issue 2, `AllFiles` is `{Foo.dfy, importFoo.dfy}` and `ToBeVerified` is `{importFoo.dfy}`, so `AssumedCorrect` is `{Foo.dfy}`. Since there are errors in `AssumedCorrect`, the verification of `ToBeVerified` may succeed even if there are errors in `ToBeVerified`, too. In other words, the errors in `AssumedCorrect` can mask errors in `ToBeVerified`. Or, to use words similar to your own above, the verification results for `ToBeVerified` depend on the correctness of `AssumedCorrect`.

As long as every file of your program is part of `ToBeVerified` in some call to the verifier, the only way you would not get any errors is if your entire program is correct. In the future, I hope that Dafny will have some package management / build system that will handle files and dependencies for you. Today, you have to manage this yourself. If you just want to make `AllFiles` and `ToBeVerified` be the same set of files, then Dafny offers you two ways to do that today. One way is to make sure you list all files on the command line and don't rely on `include` directives. You can make sure you account for all needed files if you use the `/noIncludes` flag, which has the effect of ignoring all `include` directives. This means that the program won't resolve (and you'll get an error) if you forget some file that's needed. The other way is to use the `/verifyAllModules` flag, which says to make both `AllFiles` and `ToBeVerified` all the files on the command line plus those files found through `include` directives.
