### ISSUE TITLE
datatype methods/functions and abstract modules

### ISSUE THREAD

**Issue by rtjohnso** [dafny-lang/dafny#986]
It would be nice to be able to declare the interface to a datatype in an abstract module and then define (and extend) the interface in refining modules.  This is already possible with regular functions and methods, but I don't think it's possible with datatype functions and methods.

Concretely, what I'd like to be able to do is something like this:

```
abstract module Foo {
  // Declare the interface for a datatype Bar that must be defined and implemented by refining modules.
  datatype Bar
  {
    function Something() : nat
    method DoSomething() returns (z: nat)
  }
}

module Food refines Foo {
  // Define and implement and extend the interface for Bar
  datatype Bar = Bar(x: int)
  {
    function Something() : nat { 0 }
    method DoSomething() returns (z: nat) { 0 }

    function Extension() : nat { x }
    method DoExtension() returns (z: nat) { z := x; }
  }
}
```

**Comment by RustanLeino** [comment]
This works if you change the declaration of `Foo.Bar` to be an opaque type instead of a datatype (that is, change the keyword `datatype` to `type`). An opaque type is allowed to have members, so you can declare `Something()` and `DoSomething()` like you do above. And since it's an opaque type, you're allowed to make it more specific in `Food`, like you're already doing above.

Your example is a fine use of module refinement, where you can make several modules (like `Food`) adhere to the same interface. Note, however, that if all you want is the ability to hide definitions, module refinement is overkill. Instead, I suggest you use _export sets_, which allow you to combine the two modules into one while controlling what names (using `provides` clauses) and which full definitions (using `reveals` clauses) clients of the module can see. For example, here's how you export the same things as in module `Foo` above:

``` dafny
module Foo {
  export
    provides Bar
    provides Bar.Something, Bar.DoSomething

  datatype Bar = Bar(x: int)
  {
    function Something(): nat { 0 }
    method DoSomething() returns (z: nat) { }

    function Extension(): nat { if 0 <= x then x else 12 }
    method DoExtension() returns (z: nat) { z := if 0 <= x then x else 12; }
  }
}
```

For more information about export sets, see [Modular Verification Scopes via Export Sets and
Translucent Exports](http://leino.science/papers/krml261.pdf).
